### ISSUE TITLE
Soy: Refine detection of unused parameters with {call ... data="all"}

### ISSUE THREAD

**Issue by Waxolunist** [vtst/ow#1]
If I use a data="all" directive while calling another template from within a template the error unused params is shown.

**Comment by vtst** [comment]
Ok. I'll fix this. Thanks for the bug report.

**Comment by vtst** [comment]
As a first fix, I removed all error messages about unused parameters when a call with data="all" is made in the template. This would improve the situation, as users with valid soy files will no longer have error messages. However, some errors would no longer be detected. A more fine-grained analysis should be implemented in the future.

Example:

{namespace soy_issue_1}

/*\* @param foo */
{template .useFoo}
  {$foo}
{/template}

/*\* */
{template .doNotUseFoo}
  {'foo'}
{/template}

/*\* @param foo */
{template .fooIsUsed}
  {call .useFoo data="all" /}
{/template}

/*\* @param foo */
{template .fooIsNotUsed}
  {call .doNotUseFoo data="all" /}
{/template}

**Comment by vtst** [comment]
The way the template compiler manages unused parameters in case of use of data="all" seems weird. I implemented an approach which seems reasonable to me in the codebase. I hope it will fit most users needs.
