### ISSUE TITLE
Soy: {namespace foo autoescape="false"} marks syntax error

### ISSUE THREAD

**Issue by rapodaca** [vtst/ow#10]
In one of my templates, I have a namespace declaration:

{namespace foo autoescape="false"}

Although the template compiles and seems to perform as expected, the Eclipse plugin is marking a syntax error for "autoescape" (red underline).

**Comment by vtst** [comment]
Got it. I forgot the autoescape attribute to the namespace. Fixed in the codebase, will be available in the next version.
Thanks for the bug report.
