### ISSUE TITLE
Changes to extern files don't get reloaded.

### ISSUE THREAD

**Issue by wcjordan** [vtst/ow#100]
When I change an extern file, the plugin doesn't pickup the changes unless I  restart Eclipse.

**Comment by vtst** [comment]
It is effectively not supported to change extern files. The reason for that is that every change to an extern file would require to re-compile all javascript files, what may be not very efficient. I may implement a feature to re-build extern files on demand (e.g. an entry in a menu).

**Comment by wcjordan** [comment]
A menu button for this (or including it as part of the Project > Clean task for the builder) would be very useful for me.  I'm working on an externs file for the ExtJS library and must frequently restart Eclipse when modifying it.

**Comment by vtst** [comment]
Ok, I'll implement something like that in the next version.

**Comment by vtst** [comment]
This is implemented in the code base, and will be available in the next version.

**Comment by wcjordan** [comment]
Awesome. Thanks so much.
