### ISSUE TITLE
(goog.scope) Plugin is unable to understand properies defined on the prototype in scoped section

### ISSUE THREAD

**Issue by pstjvn** [vtst/ow#104]
The plugin seem to not understand goog.scope, Example:
a.js

```
namespace.A = function() {};
goog.scope(function() {
  var p = namespace.A.prototype;
  /** compiler annotation goes here */
  p.myPropertyName;
});
```

b.js

```
function() {
  this.AInstance = new namespace.A();
  this.AInstance.myPropertyName // plugin says such property was not defined
}
```

while if I define the property outside the scoped section it works correctly.

Is it possible for this to work? goog.scope is a 'shortcut' method for those long long namespaces and is actually working with the compiler.

**Comment by vtst** [comment]
The plugin should display exactly the same error messages as the compiler. You should check the configuration of the plugin for the project (project > properties > compiler checks > check levels), and use the same as what you use when you run the Closure compiler.
With the default configuration, it seems that your code exerpt does not generate any warning.

**Comment by pstjvn** [comment]
Yeah, this is not true really, but anyways....

For reference:
file a)

```
goog.provide('test.scope.A');
/** @constructor */
test.scope.A = function() {};
test.scope.A.prototype.method2 = function(){};
goog.scope(function() {
  var proto = test.scope.A.prototype;
  proto.method1 = function() {};
});
```

and fileb.js

```
goog.provide('test.scope.B');
goog.require('test.scope.A');

/** @constructor */
test.scope.B = function() {
  this.a = new test.scope.A();
};

goog.scope(function() {
  var proto = test.scope.B.prototype;

  proto.test = function() {
    this.a.method1(); // warning here: method1 never defined on test.scope.B.a
    this.a.method2(); // no warning becaue the method is defined outside of the goog.scope!!!
  };
});
```

It is clear that this is wrong and the compiler knows how to handle it but the plugin does not. 
If both are in the same file this works (i.e. scope is correctly resolved) however in separate files gives this error (basically it does not see the methods defined in a scoped function). 

IMO it is related to how files are handled in the plugin, but this is a BUG.

Thanks anyway.

**Comment by vtst** [comment]
Thanks for the example. I just created a project with the two files, and I've no warning. I also checked that the auto-completion on this.a works correctly (i.e. the plugin knows about method1 and method2).

**Comment by pstjvn** [comment]
I have updated the plugin just before performing the test yesterday, so it is not that. Maybe something with the settings of the plugin? Is it possible to review those in xml/text format or maybe I should reset the settings and try again.

Thanks

**Comment by pstjvn** [comment]
I have removed all configs, downloaded the eclipse EE and installed the plugins anew.
Repeating the exercise now I know exactly which option triggers the problem - warning level set to Verbose. 

In my case the method was not in the auto complete list but the warning is generated only in verbose level. I do not see what else can I test to provide any useful information. I do not believe this is caused by configuration, but if it works for one (you), but not for me after clean install I do not know what else to try. 

The problem is that the scoped methods are used very much in internal projects and without them working properly the plugin is practically useless, because the devs already know the closure library apis, but they do not know our internal APIs. I would really want this wo work and I am ready to try anything really.
