### ISSUE TITLE
Soy: Using data="all" should not require parameter declaration

### ISSUE THREAD

**Issue by ismell** [vtst/ow#11]
Awesome plugin I just started playing with it :)

I got a bug for you.

```
/**
 * Creates the Viewer
 * @ param id The unique Id for the viewer
 * @ param data The set of data sources
 * @ param config Configuration options for this widget
 * @ param env Request Environment
 * @ param assets External Assets
 * @ param requestUri The URI that was used to get to the current page
 */
{template .main}
  {call .body data="all" /}
{/template}

/**
 * Creates the Viewer
 * @param id The unique Id for the viewer
 * @param data The set of data sources
 * @param config Configuration options for this widget
 * @param env Request Environment
 */
{template .body}
...
{/template}
```

My main template does not explicitly use any of the parameters but instead passes them off to another template.
This causes the following error: Missing parameter: 'id, data, config, env'.

If I add the parameters into the main template declaration I get a soy error saying I'm not using the parameters. I think the correct thing to do is ignore checking data="all" ?

Raul

**Comment by vtst** [comment]
Hi,

I saw two problems in your code:
1. In the first template, the param declaration is not well formed: there should be no space between the @ and the param keyword. Hence, id, data, config, etc. are not recognized as parameters.
2. In the first template, the parameters assest and requestUri are not used.

The following file seems to be correctly handled by the plugin:

```
{namespace issue11}

/**
 * Creates the Viewer
 * @param id The unique Id for the viewer
 * @param data The set of data sources
 * @param config Configuration options for this widget
 * @param env Request Environment
 * @param assets External Assets
 * @param requestUri The URI that was used to get to the current page
 */
{template .main}
  {call .body data="all" /}
  {$assets + $requestUri}
{/template}

/**
 * Creates the Viewer
 * @param id The unique Id for the viewer
 * @param data The set of data sources
 * @param config Configuration options for this widget
 * @param env Request Environment
 */
{template .body}
  {$id + $data + $config + $env}
{/template}
```

Does that answer to your problem?

## 

Vincent

**Comment by ismell** [comment]
Interesting...

The reason I had the space in between the `@` was that the soy compiler used to throw an error saying that `@id` was never used. It was my poor mans way of documenting with out having the compiler throw an error. I just tired removing the space so the parameters were actually found and I got no compile error.

It seems that the latest compiler now skips parameter checking if there is a data="all" in the template body.

Sorry for the bogus bug, I should try upgrading my soy compiler first ;)
