### ISSUE TITLE
Less: Couldn't resolve reference to VariableCrossReference

### ISSUE THREAD

**Issue by Defcon0** [vtst/ow#110]
Hello,

I started using the less plug-in today and it works quite well. But one thing doesn't work:

I get "Couldn't resolve reference to VariableCrossReference" when trying:

const.less

```
@yellow: #ef6800;
```

layout.less

```
body{
  background-color: grey;

  &.chrome{
    background-color: @yellow;
  }
}
```

The less files are in the same directory. Is it a bug?

Bye Defcon0

**Comment by vtst** [comment]
You need to explictely import files in less.
It should work if you add 
  import "const.less"
to layout.less

**Comment by Defcon0** [comment]
That did it, thanks. One thing I'd like to mention: If I'm correctly, it's not necessary to import a less file if it is located in the same directory as the linking file. Maybe you can take this into account in future releases :-)

**Comment by vtst** [comment]
I'm not aware that less is allowing implicit imports of files in the same directory. I just made a test with the less compilar and it did not work.

**Comment by FagnerMartinsBrack** [comment]
> ... I just made a test with the less compilar and it did not work.

@vtst See https://github.com/vtst/ow/issues/85#issuecomment-15350458
