### ISSUE TITLE
LESS : Error reported when ' !important' is used

### ISSUE THREAD

**Issue by bgaillard** [vtst/ow#112]
Hi, when I use the following LESS code an error is reported. 

```
.font-open-sans(normal, normal, 600, 16px) !important;
```

If I delete '!important' the error disappears.

The definition of 'font-open-sans' is the following : 

```
.font-open-sans (@style: normal, @variant: normal, @weight: normal, @size: 1.3em) {
    font-style: @style;
    font-variant: @variant;
    font-weight: @weight;
    font-size: @size;
    font-family: 'Open Sans', sans-serif;
}
```

![less-error](https://f.cloud.github.com/assets/1327782/196031/32a1a1ba-8007-11e2-8e39-12510725bff9.png)

Thanks, 

Baptiste

**Comment by vtst** [comment]
This is fixed in the code base, and will be available in the next release. Thanks for the bug report.

**Comment by bgaillard** [comment]
Thanks for the fix, it works like a charm !
