### ISSUE TITLE
@import without ".less" file extension does not work

### ISSUE THREAD

**Issue by derekcicerone-zz** [vtst/ow#113]
According to the documentation, an @import without the .less extension should work:

Any file that does not end with .css is considered less file and processed. In addition, if the file name has no extension or parameters, the “.less” suffix is added on the end. Both of these are equivalent:

@import "lib.less";
@import "lib";

**Comment by vtst** [comment]
Thanks for the bug report, I'll fix that.

**Comment by vtst** [comment]
Which version of the plugin do you use? Having a look to the code, it seems this has been fixed together with bug #65, released in version 1.0.7.

**Comment by derekcicerone-zz** [comment]
I'm using version 1.0.13.  It looks like #65 tracks a different issue.

**Comment by vtst** [comment]
Issue #65 indeed track a different issue, but it seems that the code change attached to it also solved this problem.
I just tested an example in my Eclipse installation, and it worked fine.

**Comment by derekcicerone-zz** [comment]
Hmm, weird, here are some more specifics from my usage in case it helps...

This line doesn't work:
@import "../../libraries/bootstrap-2.0.4/bootstrap-mixins-2.0.4";
(I get a yellow squiggly line that says "This URI cannot be resolved.")

This line does work:
@import "../../libraries/bootstrap-2.0.4/bootstrap-mixins-2.0.4.less";

Here's more info: I tried using a less file in the same directory and it works without ".less".  This only seems to occur when I try to reference a file in a different directory.  Perhaps that goes through a different code path than imports in the same directory?

I'm using the LESS plugin-in version 1.0.13 with Xtext 2.3.1 in Eclipse Juno SR2.

**Comment by vtst** [comment]
Ah ok, I see: my plugin is using the standard Eclipse function to test whether an URL has an extension (so, in your example, "../../libraries/bootstrap-2.0.4/bootstrap-mixins-2.0.4" is considered as having ".4" as extension), while LESS compiler is using some custom regexp which is not allowing digits in file extensions:
See https://github.com/cloudhead/less.js/blob/master/lib/less/tree/import.js#L61: return (this.css !== undefined || /(.[a-z]_$)|([\?;]._)$/.test(path)) ? path : path + '.less';

I'll fix that, though one may argue that the LESS compiler or its documentation is a little bit buggy here.

**Comment by vtst** [comment]
Thanks for the example!

**Comment by derekcicerone-zz** [comment]
Oh, interesting - good catch - that makes total sense!  I was way off :)

**Comment by vtst** [comment]
This is fixed in the codebase.

**Comment by derekcicerone-zz** [comment]
Cool! Thanks for the quick fix!
