### ISSUE TITLE
Less: Support for anonymous collector mixins parameter

### ISSUE THREAD

**Issue by SomMeri** [vtst/ow#116]
Next mixin is syntactically correct, but I get two errors on it:

```
.mixin-arguments (@width: 0px, ...) {
    border: @arguments;
    width: @width;
}
```
- A variable length argument cannot have a default value.
- no viable alternative at input '...'

If I add a name to the collector argument:

```
.mixin-arguments (@width: 0px, @name ...) {
    border: @arguments;
    width: @width;
}
```

I get a warning:
- A non-optional parameter should not appear after an optional parameter.

**Comment by vtst** [comment]
Fixed in the code base. Thanks.
