### ISSUE TITLE
Support for named parameters in mixin calls

### ISSUE THREAD

**Issue by SomMeri** [vtst/ow#117]
Less language has support for named parameters in mixin calls. Next snippet is syntactically correct:

```
.mixin(@a) {
   //something
}
#all-named1 {
  .mixin(@a: 11); // this is valid mixin call
}
```

It reports an error:
- mismatched input ';' expecting '{'

**Comment by vtst** [comment]
This is implemented in the code base.
As this was a pretty huge change, it would be awesome if some users could try it by compiling the new version from the code base.

**Comment by SomMeri** [comment]
I think I can test it, but I have trouble to compile the project. I'm getting a lot of compile errors. For example, `net.vtst.ow.eclipse.less.validation.LessJavaValidator` source file can not find `AbstractLessJavaValidator` class. 

What I did: I have Eclipse RCP Indigo and this:
- `git clone https://github.com/vtst/ow.git`
- import existing projects into eclipse

Target platform is Eclipse RCP Indigo and has xtext installed. 

What should I do to compile it?

**Comment by vtst** [comment]
You need to compile the grammar file by running the workflow  ow / src / eclipse / net.vtst.ow.eclipse.less / src / net / vtst / ow / eclipse / less / GenerateLess.mwe2 
If you installed Xtext plugin in Eclipse, select the file in the project explorer, right click, Run, MWE2 Workflow.

**Comment by SomMeri** [comment]
I run MWE2 Workflow on GenerateLess.mwe2 and on GenerateSoy.mwe2. It solved most problems.

All remaining problems are in net.vtst.ow.eclipse.js.closure project:
- The import org.eclipse.wst.jsdt.internal.ui cannot be resolved  
- The import org.eclipse.wst.jsdt.ui cannot be resolved
- JavadocHover cannot be resolved to a type

The root of the problem is probably this:
- Unsatisfied version constraint: 'org.eclipse.wst.jsdt.core: 1.1.0'    MANIFEST.MF /net.vtst.ow.eclipse.js.closure/META-INF
- Unsatisfied version constraint: 'org.eclipse.wst.jsdt.ui: 1.1.0'  MANIFEST.MF /net.vtst.ow.eclipse.js.closure/META-INF

I search through marketplace a bit, but I'm not sure what to look for.

**Comment by vtst** [comment]
You need the JSDT to be installed to run the closure project.
But in fact you don't need the closure project for less, so just delete it :) You need only the two easyxtext projects and the two less projects.

**Comment by SomMeri** [comment]
Just in case someone else is trying the same thing, the less.ui plugin needs bigger then default memory.
- Run As -> Run Configuration -> Eclipse Application -> Tab Arguments ->VM arguments should be: `-Dosgi.requiredJavaVersion=1.5 -Dhelp.lucene.tokenizer=standard -XX:MaxPermSize=1024m`

I just made it run and it seems ok. Unfortunately, I run out of time, so I will play with it a bit more tomorrow.
