### ISSUE TITLE
Less: Support for: Media Queries as Variables

### ISSUE THREAD

**Issue by SomMeri** [vtst/ow#118]
Media query can be interpolated from a variable. This is legal less, but I get a syntax error on it:

```
@singleQuery: ~"(max-width: 500px)";
@media screen, @singleQuery {
  set {
    padding: 3 3 3 3;
  }
}
```

**Comment by vtst** [comment]
Implemented in the code base.

**Comment by SomMeri** [comment]
Wow, that was fast. Thank you.
