### ISSUE TITLE
Less: Comparator < in guards

### ISSUE THREAD

**Issue by SomMeri** [vtst/ow#119]
The comparator &lt; causes errors:
- no viable alternative at input '&lt;'
- extraneous input '@b' expecting ')'

On input:

```
 .max (@a, @b) when (@a < @b) {
   width: @b;
 }
```

Also here:

```
.light (@a) when (@a < 50%) {
  color: black;
}
```

Note: comparator greater works ok:

```
.max (@a, @b) when (@a > @b) {
  width: @a;
}
```

**Comment by vtst** [comment]
There was a silly bug in the grammar definition. Fixed in the code base. Thanks.
