### ISSUE TITLE
Soy: Delegate templates not found

### ISSUE THREAD

**Issue by ismell** [vtst/ow#12]
I have a template that calls a delegate template

```
/**
 * Creates the Viewer
 * @ param id The unique Id for the viewer
 * @ param data The set of data sources
 * @ param config Configuration options for this widget
 * @ param env Request Environment
 * @ param assets External Assets
 * @ param requestUri The URI that was used to get to the current page
 */
{template .main}
  {delcall viewer.components.header data="all" /}
{/template}

/** Viewer Header
 * @param id
 */
{deltemplate viewer.components.header}
  <div id="{$id}" class="viewer_widget">
{/deltemplate}
```

This is currently showing a `Couldn't resolve reference to DelTemplate 'viewer.components.header'.`. I don't think it should actually perform a lookup on delegate templates because they may or may not exist, and the default templates can exist in a separate file.

Thanks,
Raul

**Comment by vtst** [comment]
Hello,

I copy-and-pasted your example on my instance of the plugin, and I did not get any error message about the del template. Which version of the plugin do you use?

## 

Vincent

**Comment by ismell** [comment]
Lol, I'm turning out to be a liar. I went back to the original template that I pulled the snippet from and it's gone. I guess something got into a bad state.

Well thanks and awesome job on the plugin :)

Raul
