### ISSUE TITLE
Less: Illegal pseudo class argument error on valid nth expression

### ISSUE THREAD

**Issue by SomMeri** [vtst/ow#120]
Error highlighter reports "Illegal pseudo class argument." error on this expression: 
- `:nth-child( -n+ 6)`.

**Comment by vtst** [comment]
From: http://www.w3.org/TR/selectors/#nth-child-pseudo
nth
  : S\* [ ['-'|'+']? INTEGER? {N} [ S\* ['-'|'+'] S\* INTEGER ]? |
         ['-'|'+']? INTEGER | {O}{D}{D} | {E}{V}{E}{N} ] S*
  ;

**Comment by vtst** [comment]
Fixed in codebase.
