### ISSUE TITLE
Support for semicolon as mixins parameters separator

### ISSUE THREAD

**Issue by SomMeri** [vtst/ow#121]
Less.js added semicolon as allowed mixins parameters separator recently. These are legal mixin calla:

```
.mixin-takes-two(@a : d, e; @b : f);
.mixin-takes-two(@a : d, e;);
```

Basically, if there is a semicolon, then all colons are considered to be list separators. If there is no semicolon, then colons are considered to be arguments separators. It works in both mixin declarations and calls.

**Comment by vtst** [comment]
This has been implemented together with issue #117.
