### ISSUE TITLE
Errors when parsing LESSHat less file

### ISSUE THREAD

**Issue by derekcicerone-zz** [vtst/ow#123]
There is a cool mixin library for LESS: http://lesshat.com/

Opening it up in Eclipse produces "no viable alternative" errors on the first non-commented-out line of the file lesshat.less.  The line is defining a variable.

**Comment by vtst** [comment]
With these two fix, I've no more parse errors. Will see if I can do something for the warnings.

**Comment by derekcicerone-zz** [comment]
Cool!  Can't wait to try this out.

**Comment by vtst** [comment]
Closing this issue, as the only remaining problem is covered by issue #125.
