### ISSUE TITLE
Collector argument should be considered optional

### ISSUE THREAD

**Issue by SomMeri** [vtst/ow#124]
The plugin assumes that collector parameter in declaration must be matched by at least one argument in call. This leads to unnecessary warnings:

```
.mixin(@a:defA, @b:defB, @c...) { // warning 1
  arguments: @a, @b;
  collector: @c;
  all: @arguments;
}
#all-unnamed2 {
  .mixin(11); // warning 2
}
```
- Warning 1: `A non-optional parameter should not appear after an optional parameter.`
- Warning 2: `The mixin '.mixin' expects 3 parameter(s) or more. 1 is (are) provided.`

Less-1.4.0-b1.js output was:

```
#all-unnamed2 {
  arguments: 11, defB;
  collector: ;
  all: 11 defB;
}
```

**Comment by vtst** [comment]
Fixed in the code base.
