### ISSUE TITLE
The plugin checks  only first found mixin for number of parameters, not all of them

### ISSUE THREAD

**Issue by SomMeri** [vtst/ow#125]
This should not show a warning, but it does:

```
.mixin(@a, @b) { all: @arguments; }
.mixin(@c) { all: @arguments; }
#all-unnamed2 {
  .mixin(11); // warning 1
}
```
- warning 1: `The mixin '.mixin' expects 2 parameter(s). 1 is (are) provided.`

**Comment by vtst** [comment]
Yes, that's a limitation of the plugin, which have been there since the first version. It is generating most or all of the warnings mentioned in issue #123.
I'll try to improve this.

**Comment by vtst** [comment]
I re-factored the code to handle this better. There might remain some refinements to be implemented.

**Comment by vtst** [comment]
Finished. Tested on LESSHat.

**Comment by SomMeri** [comment]
Thank you.

**Comment by derekcicerone-zz** [comment]
Thanks!
