### ISSUE TITLE
Less: Errors in a compilable snippet ( guard )

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [vtst/ow#128]
The folowing issues a lot of errors, but should be valid.

```
// The Grid
.generate-grid-columns(@grid-columns) {
  // Default columns
  .spanX (@index) when (@index > 0) {
    .span@{index} { .span(@index); }
    .spanX((@index - 1));
  }
}
```

My suggestion would be an option to disable completely the errors/warnings. That way we could use the tool without blocking development while issues like this are solved.

The snipped above is from https://github.com/twitter/bootstrap/blob/3.0.0-wip/less/mixins.less#L452

The offending code looks like:

```
// Multiple markers at this line
// - mismatched input '@index' expecting ')'
// - mismatched input '>' expecting ':'
// - no viable alternative at input ' '
.spanX( @index ) when ( @index > 0 ) {

}
```

**Comment by vtst** [comment]
Fixed various issues, so that the following code fragments is properly handled by the mixin:

.generate-grid-columns {
  .spanX (@index) when (@index > 0) {
    .span@{index} { foo: @index }
    .spanX((@index - 1));
  }
  .spanX(0) {}
  .spanX(2);
}

**Comment by FagnerMartinsBrack** [comment]
Thank you very much man, seriously :+1:
