### ISSUE TITLE
Soy: print directives cause errors

### ISSUE THREAD

**Issue by jensrutschmann** [vtst/ow#13]
The print directives used in the example template below give errors like:

`Couldn't resolve reference to PrintDirectiveDeclaration 'noAutoescape'.`
`Couldn't resolve reference to PrintDirectiveDeclaration 'escapeUri'.`

```
{namespace Test.Templates}

/**
 * @param someData
 * @param someUrl
 */
{template .test}
        {$someData |noAutoescape}
        {$someUrl |escapeUri}
{/template}
```

This happens with Closure Templates 1.0.0

**Comment by jensrutschmann** [comment]
Please ignore this one.

It has been caused by me modifying the file `data/builtin.soy` and entering an invalid declaration of the getText method I mentioned in ticket #15
This apparently resulted in the following declarations of the print directives being ignored.

Reinstalling the plugin solved this issue. Sorry for the noise ...

**Comment by vtst** [comment]
No problem, thanks for closing it.
