### ISSUE TITLE
Less: Error when you have a comment above mixin call

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [vtst/ow#130]
test1.less:

```
#test() {
    // do something
}
```

test2.less:

```
@import "test1.less";

// An error is issued to the call. Remove this comment and the error disappears.
#test();
```

An error is issued to the comment marked `The mixin '#test' is undefined in this context.`.
Creating a blank new line between the comment and the call acts as a workaround.

**Comment by vtst** [comment]
This was a tricky bug. Fixed in the code base.

**Comment by FagnerMartinsBrack** [comment]
@vtst 
I don't see any tests on your commits. Is this regression-safe? Or you are testing outside the repo?
I ask because that would enhance https://github.com/vtst/ow/issues/132
