### ISSUE TITLE
Less validation should be located along with regular eclipse validation

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [vtst/ow#134]
Validation > HTML Syntax
Validation > XML Syntax
Validation > LESS Syntax

**Comment by derekcicerone-zz** [comment]
This is really cool.  I had no idea I could enable/disable validation settings.  Is it possible to put the LESS validator in the list on Validation property page as well so that it can be customized?  I'd like to disable validation checks for 3rd party LESS files.
