### ISSUE TITLE
Less: allow disabling of error messages on undefined variables and mixins

### ISSUE THREAD

**Issue by MaureenD** [vtst/ow#135]
I like this plugin for the ability to use the eclipse editor with outlining and formatting but so many errors make it a problem.

Since I'm running the Less.app on my Mac, it will pick up compile errors, so is there a way to just turn off ALL error checking on the plugin?

Currently using Bootstrap and every single less file shows errors.

**Comment by FagnerMartinsBrack** [comment]
That is a known problem, but looks like the author is not willing to download and fix twitter bootstrap's issues. The hardest of them are related to the import statements.

**Comment by MaureenD** [comment]
And also the IE filter statement for gradients. Even if there was a way to remove the Xtext nature and leave in the LESS nature on a project, but I guess it's built with Xtext so that would be impossible.

**Comment by FagnerMartinsBrack** [comment]
Yeah that is for sure. Try to escape using ~"ms-vendor-syntax-here" but that would require source changes (but could be a workaround - not tested)

**Comment by MaureenD** [comment]
Sadly, I'm going to uninstall the plugin but will keep a watch on this project to see if it evolves for Bootstrap support.

**Comment by FagnerMartinsBrack** [comment]
The thing is not the lack of support for bootstrap but for less itself. The language is growing and the author activity is not that great. That is why I am suggesting https://github.com/vtst/ow/issues/132, at least that would be easy to ppl to engage on this plugin development.

**Comment by vtst** [comment]
Added options for variable and mixin checks. https://github.com/vtst/ow/commit/3c42d82dff79a1a9747390e3a745d55572e39619

**Comment by vtst** [comment]
Closing this issue, as once the mixin/variable definition checks are disabled, the only remaining error on twitter bootstrap is on an @viewport rule, see #136.
