### ISSUE TITLE
Soy: HTML style attributes with size specifications trigger invalid syntax errors

### ISSUE THREAD

**Issue by jensrutschmann** [vtst/ow#14]
Two errors like this are caused by the template below.
`required (...)+ loop did not match anything at character 'm'`

Once I replace the "." in "0.5em" with a "," (-> "0,5em"), the error message is gone.
Might this be caused by the period having a special meaning in regular expressions ?

```
{namespace Test.Templates}

/**
 */
{template .test}
        <p style="margin-top: 0.5em; padding-left: 1.5em;">abc</p>
{/template}
```

**Comment by vtst** [comment]
There is indeed an error is the parser. I just fixed it in the codebase, it will be available in the next version. Thanks a lot for the bug report.

## 

Vincent
