### ISSUE TITLE
Less - Disable validation

### ISSUE THREAD

**Issue by ssachtleben** [vtst/ow#142]
Hey,

I'm using the eclipse less plugin in my project. I have split the less files in several parts like I got a main file for site, admin and more.

Inside of the main files I split the less into multiple files like variables and for each component a file. But now I get thousands of errors because the components dont know the variables (they are included in the main files).

This behaviour is ok but I wont to disable the validation to remove this errors. I cant find in less preferences or in the validation preferences any possibility to disable the validation. How can I solve this problem?

Thanks!

**Comment by vtst** [comment]
You can disable most validation check in the project properties (Validation > LESS).

**Comment by ssachtleben** [comment]
Ah thanks didn't saw that properties. Anyways seems like it does not remove the "Couldn't resolve reference to VariableCrossReference..." errors. It seems they coming from Xtext. Is it possible to deactivate them also?

**Comment by vtst** [comment]
If you use the last version of the plugin (1.0.16), it should. You may have to rebuild your project (Project > Clean) to have the change to take effect.
