### ISSUE TITLE
Less: Opening editor fails in version 1.0.16

### ISSUE THREAD

**Issue by couchcrew-thomas** [vtst/ow#145]
Hello. I hope this is the right place to report this:

After updating the plugin from 1.0.12 to 1.0.16 opening of the editor fails:
Error message recieved: http://pastie.org/7807836
have the requirements changed since 1.0.12 ?

**Comment by vtst** [comment]
Could you please check which versions of the following plugins to you have in your Eclipse installation:
net.vtst.eclipse.easyxtext
net.vtst.eclipse.easyxtext.ui
net.vtst.ow.eclipse.less
net.vtst.ow.eclipse.less.ui

Thanks.

**Comment by couchcrew-thomas** [comment]
I have none of those installed.
If they are needed, can you please add the update site to the requirements of your LESS plugin?

**Comment by vtst** [comment]
They are normally automatically installed when you installed the LESS plugin from the update site.
Select the menu entry "Help > About Eclipse". Then click on "Installation Details" and display the "Plugins" tab. Sort the list by Plug-in ID, and look for them.

**Comment by couchcrew-thomas** [comment]
There is nothing there but "net.vtst.ow.eclipse.less.feature.feature.group"
Version "1.0.16"
Name "LESS"

I installed it via the auto updater from 1.0.12.
I also wanted to try uninstalling, but all I can uninstall is the 1.0.12 to 1.0.16 update.
Back on 1.0.12 the "Uninstall" Button is grayed out.

**Comment by couchcrew-thomas** [comment]
I've just manually deleted your less and easytext plugin JARs and the less feature.xml.
Afterwards I installed the LESS plugin from scratch and it works fine now.
So it seems that only the update process is broken.
