### ISSUE TITLE
Less: xtext nature required?

### ISSUE THREAD

**Issue by gossi** [vtst/ow#149]
I do have a php project, which are also containing less files. Of course the project icon overlay shows the 'P' for a php project.

When I opened a less file within I got asked whether I wanted to add the Xtext nature. Well, I thought "I know, less plugin is build on xtext, so say 'yes'" which installs the Xtext nature and also the xtext builder. Later I was wondering why my project icon overlay is an 'X' instead of the 'P' for php? So I closed the project, removed the xtext nature and the builder from the .project file manually. I dropped one builder, the in my case 'ugly' 'X' and .less files still work.

So, the question is, is the nature really needed? Is this something which is forced by Xtext or the less plugin? If not needed and the latter case, I may ask to remove that dialog. In the first case, should the bug be opened in the Xtext bugtracker at eclipse?

Thanks

**Comment by vtst** [comment]
I don't think it's strictly required. But with the last version of the plugin, if you decline the adding of the nature, you won't be asked again. You can also remove the nature using the contextual menu on the project in the explorer.
