### ISSUE TITLE
Less: Autocomplete less mixins

### ISSUE THREAD

**Issue by ashwinr** [vtst/ow#150]
It would be great if the autocompletion also worked on mixins. It's very useful to look at mixins from styling libraries such as bootstrap or lesshat.

**Comment by vtst** [comment]
I significantly improved the content assist proposals for mixins. There are still a few cases where it would not work, but they might be hard to fix. Let me know if this works better for you.

**Comment by vtst** [comment]
Closing this issue, as I'm releasing 1.0.18. If you still have important cases where content assist does not work in this version, please feel free to open a new issue!
