### ISSUE TITLE
Soy: unterminated {literal} issue

### ISSUE THREAD

**Issue by Axaih** [vtst/ow#153]
The use case was:
step 1-  closed 
{literal} 

{/literal}

step 2- not closed
{literal} 

-Then I got this  error:

"An internal error occurred during: "XtextReconcilerJob".
java.lang.NullPointerException: message may not be null"

I looked for the cause an apparently is the grammar to {literal}

Thanks

**Comment by vtst** [comment]
Thanks for the bug report. This is now fixed in the code base, and will be shipped with the next version.
