### ISSUE TITLE
Less Run Option does not like the 64bit version of nodejs/lessc

### ISSUE THREAD

**Issue by amezick** [vtst/ow#156]
Here is the error:
Cannot be launched because of an I/O exception
Cannot run program "/Users/USER/AppData/Roaming/npm/lessc": CreateProcess error=193, %1 is not a valid Win32 application

I can run this just fine from within the node command prompt.

**Comment by vtst** [comment]
I'm sorry, I'm not a Windows expert, but I don't think this is a specific issue to the plugin. It is just using the Eclipse/Java API to run external commands.
