### ISSUE TITLE
Error message whenever LESS syntax is checked

### ISSUE THREAD

**Issue by acelaya** [vtst/ow#158]
I have installed the plugin on Zend Studio, a PHP IDE based on eclipse.
Everithing went OK until I created a *.less file and decided to type some LESS/CSS instructions. Every time the syntax is checked and highlighted or the file is saved the IDE show an error message saying "XtextReconcilerJob has encountered a problem".

How could I solve it?

**Comment by vtst** [comment]
Sorry, but I fear I'm not able to help you. This looks like a problem specific to your installation. You should check whether you have the last version of Eclipse and Xtext installed in your system.

**Comment by moniuch** [comment]
@acelaya, have you resolved the problem? I'm stuck exactly in the same way.

**Comment by acelaya** [comment]
I'm sorry @moniuch, I haven't.
It's been a time since I started to use PHPStorm, based on WebStorm, which has native support for LESS and SASS (not only syntax hightlight, but many other operations).

**Comment by moniuch** [comment]
@acelaya Yes, sure way to go! I'm using it at home.
