### ISSUE TITLE
Syntax Highlighting: Can't change background color

### ISSUE THREAD

**Issue by ismell** [vtst/ow#16]
I can't seem to find an option to change the default background color. It seems to be stuck at white.

Thanks,
Raul

**Comment by vtst** [comment]
The default background color of Eclipse editors is managed in the global preferences:
Menu Window > Preferences, then select General > Text Editors.
Does this solve your problem?

## 

Vincent

**Comment by ismell** [comment]
I was just hoping to change the background color for the soy editor. I'm making it match my aptana theme. If it can't be changed easily I'll just revert back to the default.

Raul

**Comment by vtst** [comment]
So, this cannot be done easily in the Xtext framework. So I'm closing this issue.
