### ISSUE TITLE
LESS Feature Request: Different colors for different selector types

### ISSUE THREAD

**Issue by coredumperror** [vtst/ow#161]
It would be awesome if the LESS plugin supported more fine-grained syntax highlighting, especially for different selector types. Every other CSS editor I've used has allowed the user to choose a color for type selectors (table, div) which is different from class selectors (.class-name), and also different from ID selectors (#name). This helps the user distinguish between these different types at a glance, which helps debugging (e.g. "Why is my selector not working?? Ohhh, it's orange instead of red, because it's missing the # that I need to make it an ID selector!")

In LESS, there is of course a deeper well of selector types than in basic CSS, like inheritance (&) and mixins. I don't think this feature necessarily needs to include customization at that level, though. Simply being able to colorize standard CSS selector types differently would be enough.

**Comment by vtst** [comment]
I implemented the possibility to customize the color of root, class and hash selectors. This should fulfill most use cases.

**Comment by coredumperror** [comment]
Sweet! Will there be an new version with this feature available soon, so I can tell Eclipse to update it? I have no idea how to compile an Eclipse plugin from the raw code here on GitHub.

**Comment by vtst** [comment]
I release about once a month when there are new features. So you should have a new release shortly.
