### ISSUE TITLE
LESS: Issues regarding parser errors

### ISSUE THREAD

**Issue by coredumperror** [vtst/ow#162]
I'm seeing a lot of problems with errors reported by the LESS parser. I'm using Eclipse Kepler on OSX Mountain Lion.

For one, @import lines which bring in library-defined variables and mixins are not always headed by the parser. For example, when I first start Eclipse, all my LESS files report "variable is undefined in this context" errors for every single use a library's variable. However, opening the file and making any edit (even without saving) makes those errors (sort of) go away.

Two: when those errors "go away", they're not really gone. The little red rectangles in the file map on the right vanish, and the red circles with Xs in them turn grey, but they remain in place. And the red squares with Xs that appear in the Package Explorer for each file also remain. Worst of all, as soon as I close and re-open the editor, the errors come back completely.

In addition to these bug reports, I would like to make a feature request: Please add an option that disables the parser entirely. 

My code shop writes much of our LESS in such a way that a file need not directly import the variables it's using (we use one central LESS file that imports several others, and that central file does the library imports). So all those import errors (even if they weren't buggy) would still be annoying to see plastered over all my code.

**Comment by vtst** [comment]
Hello,

For the @import issue, I'd need a complete example to investigate what happens.
About disabling parser: this is unfortunately not possible, as syntax coloring requires parsing.

**Comment by coredumperror** [comment]
Sorry, I should have phrased my feature request better. Would it be possible to disable the error reporter? I use an external app to compile my LESS, and it reports any errors I get, so I don't need my IDE to report them.

As for the bug with errors being improperly reported, I can't seem to reproduce it any more. So that's good... sort of.

**Comment by vtst** [comment]
The problem is that if you have syntax errors in your LESS file, syntax coloring won't work. It is possible to disable problem markers in the project properties (Validation > LESS). Do you have example of errors which are not syntax errors and which cannot be disabled?

**Comment by coredumperror** [comment]
That's odd... I don't have a "Validation" section in my project properties. Maybe I disabled it by mistake while I was configuring Eclipse?

As for the errors, I wanted to disable seeing error reports for undefined variables.

**Comment by vtst** [comment]
Disabling error reports for undefined variables is possible in the tab.
