### ISSUE TITLE
LESS: nested &.~className tilde general sibling combinator not recognized

### ISSUE THREAD

**Issue by LindsayWard-xx** [vtst/ow#166]
Example: 

```
.classOne  {
  margin: 0;
  &:hover {
    background-color: @color1;
    &~.classTwo {
      display: block;
    }
  }
}
```

The "~" above is marked as not recognized even though this less file will compile to the correct css. 

This equivalent (in compiled css) but less elegant version does not complain:

```
.classOne  {
  margin: 0;
  &:hover {
     background-color: @color1;
   }
   &:hover ~ .classTwo {
      display: block;
   }
}
```

**Comment by vtst** [comment]
Thanks for the bug report. This seems to be the same issue as #151. I just checked your example with the current code base, and it seems to be fine. So everything should be fine for you as soon as version 1.0.18 is released.

**Comment by LindsayWard-xx** [comment]
Thank you!!
