### ISSUE TITLE
Xtext exceptions with v1.0.18

### ISSUE THREAD

**Issue by heldchen** [vtst/ow#167]
every save to a changed .less file produces one of the following exceptions:

![image](https://f.cloud.github.com/assets/299636/1067562/271aeeb8-13d3-11e3-9f1b-f26015e88580.png)
![image](https://f.cloud.github.com/assets/299636/1067584/36c56c84-13d4-11e3-8488-e0696731f4b2.png)

additionally, text-completion does not work anymore, and new classes/entries are not syntax-highlighted until after saving the file. editing .css files still works fine tho. using Xtext 2.4.1

**Comment by vtst** [comment]
Cannot reproduce

**Comment by paulvi** [comment]
This maybe in Eclipse 4.3.1 onwards.

This is bad issue in @Nodeclipse CoffeeScript https://github.com/Nodeclipse/coffeescript-eclipse/issues/19
