### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by max-mykhailenko** [vtst/ow#17]
When I open file few times plugin stops highlight code. Outline works fine. Reinstall didn't help. Restart didn't help. What information you need for debug?

Eclipse version: 3.7.2
Build id: M20120208-0800

**Comment by vtst** [comment]
Thanks for the bug. It seems to belong to the hard-to-dignose family.
Let's start by trying to reproduce it. Could you please send me:
1. An example of soy file that leads the problem,
2. An exact sequence of open/close you perform to have the problem.

**Comment by max-mykhailenko** [comment]
It happens after change highlight colors in plugin settings.

**Comment by vtst** [comment]
This seems to be an Xtext problem. Hence, I'm closing this issue.
