### ISSUE TITLE
@import  ../

### ISSUE THREAD

**Issue by domc1** [vtst/ow#173]
Hi there,

Apologies if already answered. I searched through 5 pages of issues but didn't spot.

I'm using this on Eclipse with PDT and RSE, looking at a remote file system.

My 
@import "variables.less"; // Custom for this template
seems to work fine - or no errors produced.

But my other Joomla/bootstrap files in a separate location imported with:
@import "../../../media/jui/less/reset.less"

generate the following error message and aren't imported for mixins etc.
! Multiple markers at this line
- This URI cannot be resolved.
- The word 'jui' is not correctly spelled

Is this due to the file location (i.e. needing ../) or perhaps its run under RSE (although seems to have no problem with this withing current directory).

Many thanks for any help

**Comment by vtst** [comment]
Is the file "../../../media/jui/less/reset.less" part of your Eclipse workspace? If not, the behavior is expected, as it is not possible (or much more difficult) to import files which are out of the workspace.
