### ISSUE TITLE
LESS: Validation settings feature request, and a minor bug report.

### ISSUE THREAD

**Issue by coredumperror** [vtst/ow#178]
First, let me say that I _love_ the new features that you've added since I last checked out this plugin. I can finally toss out Aptana Studio, now that I no longer need its CSS editor to get halfway sane LESS syntax coloring.

There's only one significant problem I can think of: it's too hard to find the settings that let you disable validation (error reporting). The fact that those settings are only applicable at the project level is too restrictive. It should be possible to apply them at the Workspace level (i.e. directly from the Eclipse preferences dialog). This will make it easier to find the settings (I wasn't even aware that there _were_ any Validation settings until I dug around in the project properties in desperation), _and_ less annoying for folks who have lots of projects.

The reason that I find the need to disable error reporting is due to issue #147. Every project my shop has uses LESS in the way described in that issue, which makes this plugin incorrectly report hundreds of errors throughout almost every LESS file we've got.

In addition, even with every project-level Validation setting disabled, there is still one type of warning that appears in my LESS editors: "Applied parameters do not match any definition of this mixin." This is a fairly minor bug, since it's only a warning, but it'd be nice to see it fixed.

**Comment by vtst** [comment]
The warning can now be disabled. For workspace-level preference, see #141.

**Comment by coredumperror** [comment]
Excellent, thank you!
