### ISSUE TITLE
LESS: Suggestion for streamlining documentation.

### ISSUE THREAD

**Issue by coredumperror** [vtst/ow#179]
I installed LESS Plugin for Eclipse today, and, in an attempt to ensure that I get the leanest possible Eclipse installation, I didn't install Xtext first. I wanted to make sure that I installed only the absolute necessities.

And, somewhat surprisingly... that worked. LESS Plugin for Eclipse works just fine, since it apparently installed its own dependencies. I'm using Eclipse 4.3.1, which might be relevant.

This means that the Installation docs on the plugin's homepage can be streamlined, by taking out the bit about Xtext. That would make installing your plugin for the first time significantly less daunting, especially for performance-obsessed programmers like myself.

**Comment by vtst** [comment]
Thanks for the suggestion. This is indeed now possible, as Xtext packages are part of the central Eclipse repository (this was not the case when this plugin was initially released). I simplified the documentation accordingly.
