### ISSUE TITLE
Soy: Line comments pattern wrong

### ISSUE THREAD

**Issue by ismell** [vtst/ow#18]
A line comment must begin at the beginning of a line or it must have a space before it.

i.e

```
/**
 * @param related - related item data
 * @param block 
 */
{template .related}
  <div class="item">
      <img src="{if $block == 0}http://example.com/{$related.afn}_40_30_q50.jpg{/if}" >
  </div>
{/template}
```

The // in the url should not be recognized as a comment.

**Comment by vtst** [comment]
Got it, I'll try to fix that shortly. Thanks for the bug report.

**Comment by ismell** [comment]
You are fast!

**Comment by vtst** [comment]
:)
This is now fixed in the codebase, and will be available in the next version.

**Comment by ismell** [comment]
Nice :)
