### ISSUE TITLE
Issue when using @import (inline)

### ISSUE THREAD

**Issue by ahoppen** [vtst/ow#180]
As of Less 1.5.0 the @import parameter "inline" is added in addition to for instance "less" or "css".
Using a line like the following
@import (inline) "myExternalStylesheet.css";
runs fine in the Less but generates an issue in Eclipse but runs fine in the Less Compiler.

**Comment by vtst** [comment]
Thanks for the bug report. This is a new feature of LESS 1.5.0 which was not yet implemented. Done.
