### ISSUE TITLE
SOY: null-safe accesses

### ISSUE THREAD

**Issue by jicasada** [vtst/ow#182]
Hi,

This code gets error in the IDE, but it compile OK.
...
<span>{$aaa?.bbb.ccc[0]}<span>
...

According to https://developers.google.com/closure/templates/docs/concepts?hl=de-DE#expressions  --> Reference data

I'm using this jars:

net.vtst.eclipse.easy.ui_0.2.7.jar
net.vtst.eclipse.easyxtext_1.0.11.jar
net.vtst.eclipse.easyxtext.ui_1.0.11.jar
net.vtst.ow.closure.compiler_0.3.0.jar
net.vtst.ow.eclipse.js.closure_0.3.0.jar
net.vtst.ow.eclipse.less_1.0.18.jar
net.vtst.ow.eclipse.less.ui_1.0.18.jar
net.vtst.ow.eclipse.soy_1.0.9.4.jar
net.vtst.ow.eclipse.soy.ui_1.0.9.4.jar

Is a bug or is a configuration problem?
Thanks you!

**Comment by vtst** [comment]
Thanks for the bug report. I extended the grammar to cover these constructs.
