### ISSUE TITLE
Marketplace entry handover

### ISSUE THREAD

**Issue by paulvi** [vtst/ow#185]
Hello Vincent 

I have created Marketplace entry 3 month ago, thinking that the project is still.

http://marketplace.eclipse.org/content/jsdt-closure

Can I pass you the ownership? Do you have Eclipse account?

**Comment by vtst** [comment]
This is my Eclipse account:
https://marketplace.eclipse.org/user/33321

**Comment by ghost** [comment]
Hello,
The requested change for the JSDT-Closure Eclipse Marketplace listing has been made.
-Edouard

**Comment by paulvi** [comment]
@ Edouard, Vincent

Thanks and closing.
