### ISSUE TITLE
LESS: Disable auto-insert of closing quotes

### ISSUE THREAD

**Issue by coredumperror** [vtst/ow#186]
I've looked and looked, but I haven't been able to find any way to tell the LESS editor to stop adding closing quote marks and curly brackets automatically while I'm editing. My muscle memory has developed such that this is an active hinderance to my work, and it's extremely annoying that there's no way to turn this off.

Please make it possible to turn off _all_ automatic typing in the LESS editor. 

Thank you for making an almost perfect LESS editor for Eclipse.

**Comment by coredumperror** [comment]
I've been using this plugin every day for months now, and I while it fulfills my needs for a LESS editor very admirably, I get extremely frustrated by its auto-typing at least a dozen times a day. It would help my health and sanity so much that I would be willing to **pay money** to expedite the creation of a feature that disables all auto-typing in LESS Editor.

_Please_ make this happen!

**Comment by vtst** [comment]
I've asked the question to Xtext developers, as this is the standard behavior of Xtext.
https://www.eclipse.org/forums/index.php/mv/msg/706108/1307050/#msg_1307050

**Comment by coredumperror** [comment]
Thanks!

I'd love to post a reply to that topic, to show additional user interest, but their forum software appears to be broken. Every time I try to reply, I get kicked back to the frontpage of the forum, and get logged out.

**Comment by paulvi** [comment]
@coredumperror Robert, Eclipse Forum is tricky recently.

But like https://github.com/eclipsesource/jshint-eclipse/issues/64

> I can bountysource 20$ on this if it helps encouraging someone to do it :)

It is always easier to say that devote resources... and hardly cover development time.

@cdietrich Christian, please join
Is there way to donate to XText ?

**Comment by coredumperror** [comment]
Thank you!!
