### ISSUE TITLE
LESS: Bogus mixin validation errors

### ISSUE THREAD

**Issue by derekcicerone-zz** [vtst/ow#188]
It seems like the latest release (10.0.19) introduced a regression in mixin validation.

With this mixin:

```
.multiple-transition(@transition-info) {
  -webkit-transition: @transition-info;
  -moz-transition:    @transition-info;
  -ms-transition:     @transition-info;
  -o-transition:      @transition-info;
  transition:         @transition-info;
}
```

This call has a validation error:

```
.multiple-transition(~"border-color 0.2s ease-in, box-shadow 0.2s ease-in");
```

But this call succeeds:

```
.multiple-transition(@transition-info: ~"border-color 0.2s ease-in, box-shadow 0.2s ease-in");
```

**Comment by ashwinr** [comment]
+1. Can you please look into it?

**Comment by dduugg** [comment]
+1

**Comment by DaSchTour** [comment]
I have a similar problem with bootstraps
#gradient.horizontal(rgba(0,0,0,0), rgba(0,0,0,0.65));
Which even breaks every autocomplete and syntax-highlight below the closing } after this statment
