### ISSUE TITLE
Plugin didn't work with zen-coding

### ISSUE THREAD

**Issue by max-mykhailenko** [vtst/ow#19]
I don't know who are guilty, but all other plugins work fine.

**Comment by vtst** [comment]
Is zen-coding this project: http://code.google.com/p/zen-coding/
?

**Comment by max-mykhailenko** [comment]
Yes. Try it, very cool plugin.

**Comment by tapazukk** [comment]
@max-mykhailenko,  It works, but not entirely correct. Try to connect with ZenCoding plugin developers.

**Comment by max-mykhailenko** [comment]
Night build of Zen Coding work normal. Thx.
