### ISSUE TITLE
Scan less files for imports

### ISSUE THREAD

**Issue by dtrunk90** [vtst/ow#190]
Example:
main.less

<pre>
@import "variables";
@import "core";
</pre>

variables.less

<pre>
@font-color: "black";
</pre>

core.less

<pre>
body {
    color: @font-color;
}
</pre>

Now Eclipse complains about the variable used in `core.less`: `The variable '@font-color' is undefined in this context.`

This is theoretically correct, but practically wrong.
Maybe scanning imported less files would fix it?

**Comment by DaSchTour** [comment]
Practically this is also correct, just the eclipse plugin doesn't recognize it!

**Comment by vtst** [comment]
This is the same as #147.
