### ISSUE TITLE
Soy: Error while using unknown Javascript function

### ISSUE THREAD

**Issue by Waxolunist** [vtst/ow#2]
I am writing confluence-plugins. So calling the i18n-function getText is unknown to closure, thus shown as error. The editor quits then parsing the rest of the template after the first error.
It should be configurable which functions will be injected at runtime.

**Comment by vtst** [comment]
Hello,

You can declare custom functions using "special" comments in your file, e.g.:

// @function foo 1

/*\* @param x
 */
{template .testFoo}
  {print foo($x)}
{/template}

If you don't want to pollute your real .soy files with such comment, you can put these comments in a dedicated .soy file of your project.

Does this answer to your question?
Cheers,

-- Vincent

**Comment by Waxolunist** [comment]
Hello Vincent 
Thx for the reply, but it does not work for me.

I got following code:

```
{template .add}
    <form id="pagefamilies-form" class="aui" method="post" action="#">
    <div class="field-group">
        <label for="servicename"> 
            {getText('pagefamilies.form.servicename.label')}:
            <span class="aui-icon icon-required"></span>
            <span class="content"> {getText('pagefamilies.form.required')}</span>
        </label> 
        <input class="text medium-field" type="text" id="pagefamilies-form-servicename" name="servicename" title="{getText('pagefamilies.form.servicename.title')}">
        <span class="aui-icon icon-inline-help"></span>
        <span class="content">{getText('pagefamilies.form.help')}</span>
        <span class="field-help hidden">{getText('pagefamilies.form.servicename.help')}</span>
        <div class="description">{getText('pagefamilies.form.servicename.description')}</div>
    </div>
    </form> 

    <h2>{getText('pagefamilies.form.expectedstructure')}</h2>

    <div id="pagefamilies-pagetree">

    </div> 
{/template}
```

After the first getText the editor quits syntax coloring. 
see: ![Error in syntax coloring](https://sites.google.com/site/booooookmarks/images/closure_editor_syntax.png)
But syntax coloring starts in the next template again correctly (Good news).
The error message is:

> Multiple markers at this line
> - Couldn't resolve reference to FunctionDeclaration 'getText'.
> - mismatched input '}' expecting '{/template}'
> - mismatched input 'pagefamilies' expecting ')'

At the end of the file I included as you suggested:

```
// @function getText

/** @Param x
*/
{template .getText}
{print getText($x)}
{/template}
```

But that gives again an error without resolving the first one. It says:

> missing EOF at '@function'

Now I am confused. What am I doing wrong. 

Can you help me out on that please.

/Kind regards
Christian

**Comment by vtst** [comment]
Thanks for the detailed error report.

In the original code, you had in fact two errors messages per {getText('...')}:
1. One because getText was not defined => adding the // @function getText 1 resolved it.
2. One because there is a bug with the parsing of print directives without the print keyword.

I'll try to fix the second bug, but it's tricky ;) In the meantime, you can work around by explicitely writing the print command, as in:
{print getText('...')}
This has the same meaning as {getText('...')}, and is parsed correctly by the plugin.

Concerning your last error message (missing EOF at '@function'), I think it is just because you forgot the '1': replace
// @function getText
by
// @function getText 1

**Comment by Waxolunist** [comment]
Hello Vincent

It works perfectly now. Adding the print-Function makes syntax-highlighting working again.

I added now a file functions.soy with following content:

```
{namespace FUNCTIONS}

// @function getText 1
```

And all errors are gone. I missed the character '1' the last time. 

I'll let this issue open because of the bug 2 you described in your last post.
But it's really a minor one, so you can close if you want. I am satisified at the moment.

Thx again

/Kind regards
Christian

**Comment by vtst** [comment]
Thanks for your feedback. I'm keeping the bug open for the issue #2.

**Comment by vtst** [comment]
The second bug is now fixed in the code base. To be released soon :)
