### ISSUE TITLE
Less: Wrong work with inline media queries

### ISSUE THREAD

**Issue by max-mykhailenko** [vtst/ow#20]
Plugin didn't know code constructions like this :

@media only screen and (min-width: 100px) {

}

It's error and I lost any autocomplite.

**Comment by vtst** [comment]
Hello,

Thanks for your feature request.
As indicated on the home page for the plugin, CSS3 selectors and media queries are not yet supported. I'll try to implement them shortly. I'll keep you posted on this issue.

## 

Vincent

**Comment by max-mykhailenko** [comment]
LESS works correctly with this code.

**Comment by max-mykhailenko** [comment]
But LESS (LESSPHP) works fine with this code.

**Comment by vtst** [comment]
I implemented support for CSS3 selectors and media queries. This will be available in version 1.02, this should solve this issue.
