### ISSUE TITLE
Support --include-path in Editor

### ISSUE THREAD

**Issue by archerzz** [vtst/ow#200]
It's a reasonable use case that when you have a set of common themes written by LESS, you would like to leverage it for all other projects. To reduce the maintenance cost, it would be better to consolidate the common themes in one place and let other projects refer to that place.
In command-line options of lessc, "--include-path" is an option to support that case. You can declare a few places where lessc will search. However, in eclipse editor, that's not supported.
Shall we consider to support "--inclue-path" in editor? I think that will be very useful.

**Comment by gossi** [comment]
I just released my transpiler-plugin, see here: https://github.com/gossi/eclipse-transpiler-plugin which can do what you are looking for. I just asked on how to cooperate with this plugin #204.

**Comment by vtst** [comment]
There is now a project property for include path.
