### ISSUE TITLE
Build error: Package 'net.vtst.ow.eclipse.less.less.impl' does not exist in this plug-in

### ISSUE THREAD

**Issue by paulvi** [vtst/ow#209]
While looking for reason of build failure #206 #208 
For ow\src\eclipse\net.vtst.ow.eclipse.less\META-INF\MANIFEST.MF

I get errors

> Package 'net.vtst.ow.eclipse.less.less.impl' does not exist in this plug-in
> Package 'net.vtst.ow.eclipse.less.less.util' does not exist in this plug-in
> and 2 more

```
Export-Package: net.vtst.ow.eclipse.less,
 net.vtst.ow.eclipse.less.formatting,
 net.vtst.ow.eclipse.less.generator,
 net.vtst.ow.eclipse.less.less,
 net.vtst.ow.eclipse.less.less.impl,
 net.vtst.ow.eclipse.less.less.util,
 net.vtst.ow.eclipse.less.parser.antlr,
 net.vtst.ow.eclipse.less.parser.antlr.internal,
 net.vtst.ow.eclipse.less.properties,
 net.vtst.ow.eclipse.less.scoping,
 net.vtst.ow.eclipse.less.serializer,
 net.vtst.ow.eclipse.less.services,
 net.vtst.ow.eclipse.less.validation
```

**Comment by vtst** [comment]
This package is generated by the Xtext generator. You've to run the MWE2 workflow to get the corresponding code.
http://www.eclipse.org/Xtext/documentation.html

**Comment by paulvi** [comment]
From what I know from https://github.com/Nodeclipse/coffeescript-eclipse
is that Maven has no way to call Xtext and @pulse00 Robert committed Xtext generated code.

Possibly @cdietrich or @michael-schnell (https://github.com/fuinorg/emt-xtext-archetype) know better

**Comment by cdietrich** [comment]
what do you mean by "call xtext"

**Comment by paulvi** [comment]
"call xtext" to generate files, or in other words how to build Xtext project with maven/tycho (without IDE)

**Comment by paulvi** [comment]
OK, example of using Xtend within tycho build is https://github.com/jeeeyul/eclipse-themes/pull/154 by @jvanzyl

**Comment by cdietrich** [comment]
there are several possibilities.
https://github.com/cdietrich/xtext-maven-example
https://github.com/svenefftinge/maven-xtext-example
in my current closed source project with build not with tycho but with apache felix bnd plugin

**Comment by michael-schnell** [comment]
Actually there is an Xtext Maven plugin you can use to generate the code:
http://kthoms.wordpress.com/2011/12/08/xtext-2-2-finally-brings-maven-support-for-xtend/
Of course it requires to use Maven Tycho for the build.

I haven't tried it out yet - I simply added the generated Java source code to the GIT repo (Poor man's solution, until I find the time to use the plugin).

**Comment by paulvi** [comment]
@michael-schnell It does not matter how the solution was created, but whether it solves and is kept updated.

ref https://github.com/cdietrich/xtext-maven-example/issues/2
