### ISSUE TITLE
Cannot run program "lessc"

### ISSUE THREAD

**Issue by christierney402** [vtst/ow#213]
I installed this plugin via the Eclipse Marketplace.

I then installed LESS compiler via your website link and verified that the path was included in the environment variables for Windows and that I can run "lessc" from the command prompt outside of that directory.

I then restarted Eclipse (packaged with Adobe ColdFusion Builder 3).

As per the limited instructions provided on your site I added a new launch configuration as follows:
- LESS command: lessc (existing)
- Compress the generated CSS file (existing)
- Use this launch configuration as default

When I click on my main .less file and click "Run" the following dialog appears:

"Problem Occurred

Cannot be launched because of an I/O exception

Cannot run program "lessc": CreateProcess error=2, The system cannot find the file specified"

I updated the LESS command to "lessc.cmd", which I have installed under my npm directory. Not sure if it was installed with your link or not. It now works.

Also, how do I specify the where the resulting .css file should be saved?

**Comment by DarkNami** [comment]
Your have to change the "LESS Command".
Please filling your "lessc" physical path, just like "C:\Users\[Yourname]\AppData\Roaming\npm\lessc.cmd" 
(Windows 7, node.js standard installer)

**Comment by jastorgalj** [comment]
1.- Your have to change the "LESS Command".
Please filling your "lessc" physical path, just like "C:\Users[Yourname]\AppData\Roaming\npm\lessc.cmd"   (same DarkNani)

2.- in C:\Users\Juan\AppData\Roaming\npm\node_modules\less\bin inside "switch (arg) {" put folllowing lines:

case 'O0'
case 'O1':
case 'O2':
break;

**Comment by odyodyodys** [comment]
Please reopen this, @jastorgalj's solution (big thanks!!) works but its not permanent or pretty.
