### ISSUE TITLE
Add smart support for imports from a main file

### ISSUE THREAD

**Issue by christierney402** [vtst/ow#215]
My main .less file that compiles into CSS includes imports both from the current directory and another directory (bootstrap).

Currently if I edit a file, and it is included in this main file, it doesn't look for the imports from that main file. Please add support to look for imports from a main file.

For example:

mysite.less
@import "bootstrap/less/variables.less";
@import "varaibles.less"
@import "photoGallery.less"

photoGallery.less
@media screen and (max-width: @screen-xs) {}

returns error: The variable '@screen-xs' is undefined in this context.

expected result: No error since the variable is contained in 'bootstrap/less/variables.less'

workaround: add '@import "bootstrap/less/variables.less";' to the photoGallery.less file (not a good solution)

**Comment by vtst** [comment]
This is the same as #147.
