### ISSUE TITLE
LESS update: missing requirement

### ISSUE THREAD

**Issue by mindrones** [vtst/ow#216]
First off, thanks a lot for this release :)

When trying to update, I get this error:

  Cannot complete the install because one or more required items could not be found.
  Software being installed: LESS 1.0.20 (net.vtst.ow.eclipse.less.feature.feature.group 1.0.20)
  Missing requirement: net.vtst.ow.eclipse.less 1.0.20 (net.vtst.ow.eclipse.less 1.0.20) requires 'bundle org.eclipse.jface 3.9.1' but it could not be found
  Cannot satisfy dependency:
    From: LESS 1.0.20 (net.vtst.ow.eclipse.less.feature.feature.group 1.0.20)
    To: net.vtst.ow.eclipse.less [1.0.20]

Regards.

**Comment by DaSchTour** [comment]
I would recommend not to update at all! Version 1.0.20 kills your eclipse installation! After updating my eclipse crashes directly after starting!

I had to completely reinstall my eclipse because even removing the plugin didn't help. So 1.0.20 might destroy your workspace and will need complete reinstallation and reconfiguration of Eclipse!

**Comment by vtst** [comment]
@mindrones: Which version of Eclipse do you have? Normally Kepler comes with jface 3.9.1.

**Comment by mindrones** [comment]
@vtst hi, I use 4.2.2 (Juno), I've totally missed out the Kepler release. :)
Never had the time to check out the newer eclipse releases, sorry.
I'll try to install Kepler+LESS and will report back, thanks!

**Comment by mindrones** [comment]
Just to confirm: I have just downloaded Luna RC2 and installed LESS: all went well. Thanks!

**Comment by vtst** [comment]
Cool, thanks!

**Comment by steros** [comment]
I'm  using ZendStudio and as this is using Eclipse 3.8 as a basis currently the installation fails too. Using plugin version 1.0.19 works thou.
But it would be nice to include jFace or give a reference where I could download it so I can use the latest plugin version too.
