### ISSUE TITLE
Cannot run program "lessc": error=2, No such file or directory

### ISSUE THREAD

**Issue by hellochar** [vtst/ow#231]
My usual workflow is to have a Java server running (through Eclipse), edit a LESS file, refresh my web browser and see the style changes. Occasionally the changes will just stop showing up. Looking into the compiled css files shows that they're not getting the new LESS changes. If I stop the server and try running again, I get an error box:

```
Cannot be launched because of an I/O exception

Cannot run program "lessc": error=2, No such file or directory
```

This prevents me from rerunning the server. Usually a clean or restart of Eclipse will fix the issue. My error log shows me errors which I filed in #230, but there aren't any errors around the time the LESS files stop building.

**Comment by hellochar** [comment]
Sorry! This issue is unrelated to your plugin.

**Comment by isaacjumac** [comment]
Hi,  @hellochar . May I know how you resolved your issue? I'm encountering the same issue.

**Comment by bmomani1** [comment]
you need to do install node-less on your machine, so you able to generate js and css

`sudo apt-get install npm && sudo npm install -g less`
