### ISSUE TITLE
Id with a dot inside generates error messages: "no viable alternative at input '\.login'" and "extraneous input ' ' expecting '{'"

### ISSUE THREAD

**Issue by burka** [vtst/ow#233]
This simple fragment will cause a error during validation but shouldn't:

```
#poll\.viewPoll {
}
```

**Comment by JanThiel** [comment]
Namespacing is also directly affected by this issue. Quite annoying as my code is full of "phantom errors" ;-)

Take this code from Twitter Bootstrap Mixin Library we use. It's a defined function which is namespaced.

``` css
.element {
    #gradient.vertical(#fff,#000);
}
```

Generates all of the following errors which should not happen:
![eclipse-less-validation-fail](https://cloud.githubusercontent.com/assets/3857275/4218718/13a25c62-38f4-11e4-8437-7787885e7594.png)

Brgds

Jan

**Comment by burka** [comment]
This issue is to old and nobody seems to care, so as I don't use this anymore for years, I closed it :-) Thanks.
