### ISSUE TITLE
Soy: indent with 2 spaces

### ISSUE THREAD

**Issue by pavel-stehlik** [vtst/ow#238]
Hi,
could you add option for format code with spaces instead of tabs?

I found SoyFormatter and add this, but i dont know how to build eclipse soy plugin from your sources :-/

```
@Inject(optional = true)
private IIndentationInformation indentInfo = new IIndentationInformation() {
  public String getIndentString() {
    return "  ";
  }
};
```

   public IIndentationInformation getIndentInformation() {
     return indentInfo;
  }

Thanks
Pavel

**Comment by FagnerMartinsBrack** [comment]
The identation is configured inside eclipse, look for TextEditor option and configure the proper file type.

**Comment by pavel-stehlik** [comment]
Thanks, i didnt realize, that i could setup global TextEditor.

**Comment by WORMSS** [comment]
@FagnerMartinsBrack how do you make it so less files are 2 spaces, but everything else is 4 spaces?
I need global to be 4, but less be 2 spaces ??

**Comment by FagnerMartinsBrack** [comment]
@WORMSS I haven't been using Eclipse for 2 years so I don't know, sorry.
