### ISSUE TITLE
xtext 2.7 results in anoying warning message on every edit...

### ISSUE THREAD

**Issue by pbvahlst** [vtst/ow#240]
Every time a edit is made in the less editor a warning pop-up occurs saying: "The resource is currently edited in another editor, do you want to continue?"

According to this link it should be a problem caused by a change in xtext
https://www.eclipse.org/forums/index.php/t/827695/

**Comment by mic-kem** [comment]
I have the same problem with Eclipse Luna and the most recent plugins.

**Comment by vtst** [comment]
Thanks for the bug report. Backward compatibility issue of xtext 2.7. Fixed in the code base.

**Comment by pbvahlst** [comment]
Thank you. Will this be included in a official release any time soon, so we update through eclipse :-)

**Comment by kachkaev** [comment]
Does anyone know any temporal workarounds? Anything that can at least reduce the frequency of messages would be very handy before the official plugin update.

**Comment by vtst** [comment]
FYI I'll release the new version tomorrow.

**Comment by vtst** [comment]
The new version has just been released.

**Comment by EnglishCriminal** [comment]
I am seeing this behavior in version 2.82v20154100559.
