### ISSUE TITLE
Eclipse message: “Resource was edited concurrently”

### ISSUE THREAD

**Issue by kachkaev** [vtst/ow#241]
I just installed the plugin for Eclipse Juno and could play with a few LESS files – syntax highlighting and autocomplete work as I expected. However, any time I try to edit a .less file, I get the following Eclipse modal window:

![Resource was edited concurrently
The resource is currently edited in another editor. Do you want to continue?](https://cloud.githubusercontent.com/assets/608862/4809400/368098de-5eab-11e4-806a-af57891e41d3.png)

It keeps appearing almost with every keystroke in a .less file. I can’t figure out neither the reason for such strange behaviour nor the ways to avoid it. Cleaning eclipse workspace or starting it with `-clean` option does not help. This seems like a bug of the less editor plugin, because the window appears even if only one editor with one file is open.

According to a recent unanswered question on stackoverflow (http://stackoverflow.com/questions/26544212/install-eclipse-less-plugin-resource-was-edited-concurrently), this issue can be new or just rare.

Here are my eclipse installation details, just in case:
![screen shot 2014-10-28 at 15 09 12](https://cloud.githubusercontent.com/assets/608862/4809473/09605d16-5eac-11e4-86c7-7a3e66627c71.png)

**Comment by vtst** [comment]
This is the same as #240. It is already fixed in the codebase, and will be released soon.

**Comment by kachkaev** [comment]
Cool! When about are you planning to issue the release? Just want to figure out if it's worth building the plugin myself or simply wait.

**Comment by vtst** [comment]
The new version has just been released.
