### ISSUE TITLE
Less: Code formatter

### ISSUE THREAD

**Issue by juanfeh** [vtst/ow#25]
the formatter inserts new white spaces in each execution

**Comment by vtst** [comment]
Hello,
Thanks for the bug report, This is because I did not implement yet a code formatter for the language. Sorry for not having mentioned it in the list of unimplemented features. I'll try to do it in one of the next release. Are you interested in the Soy plugin or the Less one?

-- Vincent

**Comment by pogo19** [comment]
Hi, I miss code-formatting as well. I am using the less plugin.

**Comment by vtst** [comment]
I implemented a first version of the formatter in the version 1.0.5 of the plugin I released today. Please let me know if there are any aspect of the formatting you think I should improved. (This is not an easy task, especially because it might be a matter of taste.)
