### ISSUE TITLE
Soy: Wrongly parse foreach

### ISSUE THREAD

**Issue by tapazukk** [vtst/ow#27]
Error  text:

_Multiple markers at this line
- no viable alternative at input '}'
- no viable alternative at input '['_

Code example:

``` javascript
 {foreach $i in [0,1,2]}
     {$i}
 {/foreach}

```

**Comment by vtst** [comment]
Thanks a lot for the useful bug report!
According to the documentation of Closure Templates (https://developers.google.com/closure/templates/docs/commands#foreach) only a data reference should come after "foreach ... in". But I just checked the source code for the compiler, and you're right, any expression is accepted.
So I fixed the plugin to handle properly this case. The change is submitted in the Git repository, and will be available in the next release of the plugin, hopefully by the end of the week.

**Comment by vtst** [comment]
Fixed in the codebase.
