### ISSUE TITLE
Less: Importing a CSS file breaks function creation.

### ISSUE THREAD

**Issue by mctrafik** [vtst/ow#29]
I have two imports.

@import "general.less";

and

@import "other-stuff.css"

Having the second css file states that further code has variables not defined in the scope.

I have to have the CSS file, because the following don't parse:

@keyframes fadeOut {
    0% {opacity: 1;}
    100% {opacity: 0;}
}

even though it's valid css3.

**Comment by vtst** [comment]
Thanks for the bug report. I effectively did not implement correctly the specification given at http://lesscss.org/#-importing for import statement. I fixed it, so that imported CSS stylesheets are no longer parsed. The fix should be available in the next release.

**Comment by mctrafik** [comment]
Thank you. :) Looking forward to the release.

**Comment by mctrafik** [comment]
Thank you. :) Looking forward to the release.

**Comment by mctrafik** [comment]
Thank you. :) Looking forward to the release.

**Comment by vtst** [comment]
Included in version 1.0.5 released today.
