### ISSUE TITLE
Soy: Multi-file dependency resolution

### ISSUE THREAD

**Issue by pstrinic** [vtst/ow#3]
Is there a way to support a case where a template calls a template that's contained in another soy file? 
In our particular case they are not even in the same Eclipse project. 

Example:

---
## foo.soy

{namespace foo}

/**
- Main Template
  */
  {template .Main}
  {call bar.Main}{/call}
  {/template}

---
## bar.soy

{namespace bar}

/**
- Main Template
  */
  {template .Main}
  I am Bar!
  {/template}

**Comment by vtst** [comment]
This normally works out-of-the-box for files in the same project.
For files in different project, you need to declare a reference from the user project to the provider project (select the project in the project explorer, right click, Properties and then Project References).
Does it answer to your question?

**Comment by pstrinic** [comment]
That does appear to work.

On a separate note, is there anything concrete that would prevent this plugin working with Helios?

Thank you!

**Comment by vtst** [comment]
I fear it would not work on Helios: it is using a recent version of Xtext which is not compatible with Helios.

**Comment by vtst** [comment]
Issue is closed.
