### ISSUE TITLE
Less: allow @arguments inside functions.

### ISSUE THREAD

**Issue by mctrafik** [vtst/ow#30]
The documentation for parametric mixins (http://lesscss.org/#-parametric-mixins) states that @arguments can be used inside functions.

Currently the parser complains that '@arguments is not defined in this context'

For example:

.box-shadow (@x: 0, @y: 0, @blur: 1px, @color: #000) {
  box-shadow: @arguments;
  -moz-box-shadow: @arguments;
  -webkit-box-shadow: @arguments;
}

**Comment by vtst** [comment]
I've implemented this feature, which will be available in the next release.

**Comment by vtst** [comment]
Included in version 1.0.5 released today.
