### ISSUE TITLE
Less: Creating a run configuration to compile .less files to .css

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#35]
Hello. I'm a little confused as to how to create a generic run configuration that I can use to compile any arbitrary .less file to .css. When I try to create a run configuration, I specify the location of the lessc compiler, but the configuration dialog is demanding that I specify an Input File. If I don't then when I right-click a .less file and choose the LESS run configuration it complains that the file can't be found. It seems that you have to create a run configuration for every file you want to compile. Is that the case? Or can I put some regex in the Input File field (e.g. %1 or $*, etc.) to get the configuration to recognize that I want it to compile the file that I've selected.

Also, I'm using a lessc compiler on Windows, not a *ix compiler. The lessc compiler on Windows takes a -compress option, which instructs the compiler to generate compressed .css. The run configuration has this as a configuration parameter as well. How does this configuration work? Is there a way I can pass the -compress option to the compiler? Can I just include -compress in the LESS command? Or will checking the compression box actually created compressed CSS? Thanks much.

**Comment by vtst** [comment]
> When I try to create a run configuration, I specify the location of the lessc compiler, but the configuration dialog is demanding that I specify an Input File. If I don't then when I right-click a .less file and choose the LESS run configuration it complains that the file can't be found. It seems that you have to create a run configuration for every file you want to compile. Is that the case? Or can I put some regex in the Input File field (e.g. %1 or $*, etc.) to get the configuration to recognize that I want it to compile the file that I've selected.

If you want a default run configuration, you can leave the "input file" field empty, and check the box "Use this launch configuration as default". Then, save the launch configuration, close the dialog box, select the .less file you want to compile, and select Run As > LESS compiler in the contextual menu. The compiler will be run automatically on the file you selected, with the settings of your default launch configuration.

> Also, I'm using a lessc compiler on Windows, not a *ix compiler. The lessc compiler on Windows takes a -compress option, which instructs the compiler to generate compressed .css. The run configuration has this as a configuration parameter as well. How does this configuration work? Is there a way I can pass the -compress option to the compiler? Can I just include -compress in the LESS command? Or will checking the compression box actually created compressed CSS? Thanks much.

This command line option is not supported yet. It is new in the last version of Less. I'll add it in the next version of the plugin.

**Comment by mchiocca** [comment]
I'm using a .cmd file that invokes a .wsf like so.

@cscript //nologo "%~dp0lessc.wsf" %*

The lessc.wsf is being invoked correctly by the run configuration, but it's expecting a file (i.e. %*). When I execute the run configuration I get the following error.

lessc.wsf: no input files
Usage:
  Single file: cscript //nologo lessc.wsf input.less [output.css] [-compress]
  Directory:   cscript //nologo lessc.wsf inputdir outputdir [-compress]
A failure occurred when running the LESS compiler, see above error message.

So the run configuration doesn't seem to work for me.

**Comment by vtst** [comment]
Sorry, but I don't really understand what the .cmd file is (I'm not so used to Windows). Could you please detail a little bit?
Basically, the command that you specify in the run configuration as less compiler should accept exactly the same parameters as the less compiler, otherwise it will fail.

**Comment by mchiocca** [comment]
The lessc.wsf file does the actual work using less.js. The .cmd file is just for providing an executable that invokes the .wsf file, passing the named file via %*. So basically it works like this.

C:> lessc styles.less styles.css

This compiles styles.less and creates styles.css as a result. If -compress is added as an option, then the generated .css is compressed.

Is that not what the run configuration is doing? Note that in the run configuration I've done what you've asked, leaving the input file field empty and checking the use launch configuration as default.

When the lessc.wsf is invoked, there appears to be no input file provided, apparently because the input file field in the run configuration is blank. So I'm left wondering how to get the run configuration to work.

**Comment by vtst** [comment]
The run configuration is invoking the command lessc styles.less styles.css (if "lessc", "styles.less" and "styles.css" are respectively the command, the input file and the output file you specified in the launch configuration).

In order to debug the issue, we should first clarify whether it is a problem in the automatic setting of the input file, or in the invocation of the less compiler. Could you please try to launch the configuration by explicitely specifying an input file and an output file?

**Comment by mchiocca** [comment]
I tried all sorts of variations for supplying both the input file and output file. I used the input/output file fields to no avail. I even tried providing the file names in the less compiler command and that didn't work. I got file I/O errors saying that the file could not be found. I got other errors saying that the project and resource needed to be in the file name. Nothing I did seemed to work. I couldn't get the run configuration to work at all.

**Comment by vtst** [comment]
Could you please run a launch configuration with well defined inputs and outputs, and copy and paste the full error message you get?

**Comment by mchiocca** [comment]
I don't really get an error message from Eclipse so much as I'm getting an error message from the lessc compiler itself. I get the following in the Console window.

lessc.wsf: no input files
Usage:
  Single file: cscript //nologo lessc.wsf input.less [output.css] [-compress]
  Directory:   cscript //nologo lessc.wsf inputdir outputdir [-compress]
A failure occurred when running the LESS compiler, see above error message.

I specify the compiler as C:\lessc\lessc.cmd and I use the Browse button to select a .less file for the Input File field. The Output File field is filled in automatically when you specify an Input File.

The lessc.cmd file invokes the lessc.wsf file passing arguments via %*. It looks like the Input File is not being passed in the invocation of the Run Configuration at all.

**Comment by vtst** [comment]
Ok. So the problem is probably in the command line which is generated by the plugin to run the compiler.
Could you give me an example of command line which works for invoking the less compiler in a shell window (out of Eclipse)?

**Comment by mchiocca** [comment]
Refer to the following blog.
http://blog.dotsmart.net/2010/11/26/running-the-less-js-command-line-compiler-on-windows/

I'm using the LESS compiler from duncansmart (github link is listed in the blog).

The command is
C:> lessc styles.less styles.css [-compress]

If you provide the -compress option the generated CSS is minified. Hope that helps.

**Comment by vtst** [comment]
I had a look to the code of the compiler you're using, I think the problem comes from the fact that it expects to have the input and output file names as the first and second command line arguments. (see https://github.com/duncansmart/less.js-windows/blob/master/lessc.wsf#L88)
I modify the code of the plugin to do that. However, the right thing to do would be to fix the script lessc.wsf.

**Comment by vtst** [comment]
Could you please check whether it now works?

**Comment by mchiocca** [comment]
Hello. Your change seems to have worked. I noticed that you put the .less file first, followed by the .css file, and lastly, the options. I ran a run configuration explicitly providing input/output file names and it worked. I also modified the run configuration by removing input/output file names so I could right-click and just select Run as -> LESS Compiler and that worked too. I'm closing this issue for now. I'll keep trying the Run Configuration and if I find any other issues I'll report them separately. Thanks for accommodating Windows in addition to *ix LESS compilers.

**Comment by mchiocca** [comment]
FYI - I changed lessc.wsf so that it accepts the --compress option instead of -compress so now I can use that option in my Run Configuration.

**Comment by bnguyen82** [comment]
Hi all, 
I install lessc from npm on Window and can run lessc in command line. So what I should put in field "Less command" and "Input file" in order that I can right click a master less file to run multi files which refer each other? I try putting empty on "Less command" and a less file "/my-web/src/main/webapp/less/common.less" in "Input file", check Run as default and hit Run, Eclipse show an error: 

"Cannot be launched because of an I/O exception. 
Cannot run program "": CreateProcess error=87, The parameter is incorrect"

Thank for your help.

**Comment by andreagosto** [comment]
Hi, is possible to set an absolute path for the output file? i tried but i get a java.lang.NullPointerException
