### ISSUE TITLE
Less: Code formatting option for .less files?

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#37]
According to the LESS plugin web site, version 1.0.5 includes a first cut at implementing a code formatter. Normally, there is a Source -> Format menu item for this, but I don't see this when I'm editing a .less file.

I tried using Ctrl-Shift-F5, which did something. It looks like it applied some kind of formatting, but the problem is that it stripped out all of my comments except for the initial comment block at the beginning of the file.

Is Ctrl-Shift-F5 the way to invoke the formatter? I don't see a way where you can configure how the code gets formatted. Is this customization simply not implemented yet? You can do this for other languages, such as Java and PHP.

**Comment by vtst** [comment]
Select the code you want to format in the editor, open the contextual menu, and select "Format".
In my Eclipse instance, there is also a keyboard shortcut (CTRL+SHIFT+R).

**Comment by mchiocca** [comment]
Yes. Got it. Highlighting the code you want to format and right-clicking presents you with a contextual menu that includes a Format option with a keyboard shortcut Ctrl+Shift+F. One problem though is that any comments that are included in the region you select are completely removed when you do the formatting. That includes both single line (//) and multiple line (/\* .. */) comments.

**Comment by vtst** [comment]
Embarassing bug. I opened issue #41 to track it. I'll try to fix it shortly.
