### ISSUE TITLE
Less: Syntax coloring of mixins, mixin parameters, and variables

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#38]
Currently, the declaration and use of a mixin is not colored and there is no option for adding a color either. So, mixins appear in the default color, which is set to black. The definition and reference of a mixin should have color. Also, the mixin parameters are colored. Looks like the same color as a variable declaration, which makes sense. But, the use of the parameter in the definition of the mixin has no color. It too defaults to black, which is actually true for all variable references as well. These too should be colorized.

**Comment by vtst** [comment]
This is a good point, thanks for pointing it.
I implemented some highlighting in the code base, it will be available in the next version. By default, mixin and variable definitions will be formatted in bold blue, and mixin and variable uses in regular blue.

**Comment by mchiocca** [comment]
I pulled your code and verified that the colorization is working. Looks very nice. Thanks!

**Comment by mchiocca** [comment]
Under Windows -> Preferences -> Less -> Syntax Coloring the following appears for mixin calls and variable use.

!highlighting_MIXIN_CALL!
!highlighting_VARIABLE_USE!

Both are the same dark blue color and neither is bold, which I think is correct. However, shouldn't something more human readable appear here in Preferences? Something like "Mixin call" and "Variable use" instead?

**Comment by vtst** [comment]
I forgot to define the display names for the new highlighting classes. Fixed.
