### ISSUE TITLE
JS: Custom extern files

### ISSUE THREAD

**Issue by deno** [vtst/ow#39]
There’s currently no way to specify custom extern files, which spawns number of "Bad type annotation. Unknown type Foo" warnings.

**Comment by vtst** [comment]
Hello,

Is the bug about the JavaScript / Closure plugin?
If so, it is possible to specify custom extern files: select the project in the explorer, open its properties, and go in the section "JavaScript / Closure / Includes". Does it work for you?

## 

Vincent

**Comment by deno** [comment]
It’s there, and it works perfectly… I’ve no idea how I’ve missed that. Sorry about that :-)

**Comment by vtst** [comment]
No problem, thanks for the feedback.
