### ISSUE TITLE
Less: Incomplete handling of & in selectors

### ISSUE THREAD

**Issue by gossi** [vtst/ow#4]
Hey there,

my less outline is broken. I have less code like this:

```
.t-a {
  prop: value;

  &-sub {
    prop: value;
  }

  &-sub2 {
    prop: value;

    &-level3 {
       ..
    }
  }
}

.t-b {
  prop: value;
}
```

and my outline looks like this:

```
- .t-a
`+ &
    `+ sub
        `+ &
            `+ sub2
                `+ &
                    `+ level3
                        `+ &
                            `+ .t-b
```

Instead I excepted something more like this:

```
- -t-a
|- -sub
|+ -sub2
|    `- level 3
`- .t-b
```

Would be cool to see that fixed, I tried it because of the outline :)

Thanks very much

**Comment by vtst** [comment]
Hello,

Thanks for the feedback.
The outline is broken because "&-sub", "&-sub2" and "&-level3" are not recognized as valid selectors by the plugin. You should have error markers for them. If you replace them by "&:sub", "&:sub2" and "&:level3", the outline is correct.
I did not find the "&-something" syntax documented on lesscss.org. Do you have some pointer about it?

-- Vincent

**Comment by gossi** [comment]
They are doing something else. From

```
.class-selector {
  prop: value;

  &-ext {
    prop2: value2;
  }
}
```

into:

```
.class-selector {
  prop: value;
}

.class-selector-ext {
  prop2: value2;
}
```

The ampersand (&) gets replaced with the parent selector whatever else is appended to it. I found it documented here: 
"Notice the & combinator—it’s used when you want a nested selector to be concatinated to its parent selector, instead of acting as a descendent."
http://lesscss.org/#-nested-rules

**Comment by vtst** [comment]
Ok. Thanks for the pointer. I'll implement this in the next version to come beginning of March.

**Comment by vtst** [comment]
This is fixed in the code base. Will be available in the upcoming next release!
