### ISSUE TITLE
JS: Closed projects cause exceptions

### ISSUE THREAD

**Issue by deno** [vtst/ow#45]
If there are multiple project, for example _closed_ PyDev project next to OW JS project, the following error occurs:

  Errors occurred during the build.
  Errors running builder 'Closure JavaScript Builder' on project 'javascript-project'.
  Resource '/other-project' is not open.
  Resource '/other-project' is not open.

**Comment by vtst** [comment]
Thanks for the bug report. Closed projects were not correctly handled in the plugin, and caused exceptions. I tried to fix the code (at least to avoid exceptions), this will be available in the next version.

**Comment by vtst** [comment]
Version 0.2.2 released!
