### ISSUE TITLE
Less: Multiple error messages for undefined mixins

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#46]
If you reference an undefined mixin and hover over the mixin call, you get a message that says "The mixin 'null' expects 0 parameter(s). 1 is (are) provided."

If you hover over the small red 'x' that appears to the left of the line number of the mixin call you get "Multiple markers at this line." The first is the above message. The second is "The mixin '.border-radius' is undefined in this context."

Note the 'null' in the first message. I would expect just the second message alone for the use of or reference to an undefined mixin. I would not expect an additional message about parameters since the mixin is undefined.

Update: This is for a mixin call that takes arguments for parameters. if the mixin call takes no arguments, then you just get the "undefined mixin" error message.

**Comment by vtst** [comment]
Thanks for the bug (or misfeature) report. I modified the code so that you get only one error message.
