### ISSUE TITLE
Less: Multiple markers at this line with variable declaration

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#47]
Here is an example taken from a Bootstrap .less file.

```
textarea {
    .box-shadow(inset 0 1px 1px rgba(0,0,0,.075));
    @transition: border linear .2s, box-shadow linear .2s;
    .transition(@transition);
}
```

On the definition of the variable at line 2 you get "Multiple markers at this line"
1. Mismatched '.2s' expecting '}'
2. No viable alternative at '.2s'
3. Mismatched input 'box-shadow' expecting '}'
4. No viable alternative at input ','

Is this not a correct definition for a variable inside a CSS block?

**Comment by vtst** [comment]
Thanks for the bug report.
The problem was that comma-separated terms were not correctly handled in variable definitions. I fixed the parser in the code base so that you can put exactly the same thing after a variable definition "@foo:" than after property "foo:".
