### ISSUE TITLE
Less: Add syntax coloring for all numeric literals

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#48]
The syntax coloring is nice, but could be improved. Can you add coloring to all numeric literals? I did this locally to see how it would look using green, EasyTextAttribute(0, 127, 0, SWT.NORMAL) and it looked pretty good. I tried to apply a semantic rule to grammar.getNumericLiteralRule(), but that didn't work. I had to use bindTerminalRule() for each numeric literal terminal rule in the grammar. If you apply a general semantic rule (and if you can get that to work) you can only have one color for all literals. If you bind each terminal rule separately at least you can vary the color based on the type of literal. I used 'Numeric literal' in the Syntax Coloring preferences.

**Comment by vtst** [comment]
Thanks for the proposal. However, I'm unsure whether this should really be done. On the one hand, why decorating numeric litterals, and not other kinds of literal. On the other hand, if we decorate all literals, everything will be decorated, so it will not really help navigating the code.
In other Eclipse plugins (e.g. Java, JavaScript, etc.), numeric literals are not decorated.

**Comment by mchiocca** [comment]
Yes, I suppose. The syntax coloring is just a little plain. With the exception of the small number of items that are decorated, everything else is colored using the default black color. So, the RHS of most properties is completely black. Colorizing numeric literals (e.g. 13px, .5em, 0, .2s, etc.) helps break up the RHS and make numeric literals stand out much more. As I mentioned, I did try it and it seemed to look OK. So, I thought it might be a worthwhile suggestion. I'll defer to your discretion though, so if you decide not to colorize, then I guess that's OK. Thanks.

**Comment by mchiocca** [comment]
Actually, coloring numeric literals does make the .less files a little easier to read. Everything else is black, such as keywords (e.g. inherit, auto, inline, block, none, etc.) as well as all punctuation and other symbols. PHPStorm does some colorization beyond what your plugin does and it looks OK. But, as I said, I'll leave it up to you to decide.

**Comment by vtst** [comment]
I just implemented this. By default, numeric literals are colored as regular text, but this can customized in the editor preferences.

**Comment by mchiocca** [comment]
Great! Thank you! Default black is fine. I changed the preference setting to bright red and it really makes a difference. One thing I noticed though was that you did not mention the new coloring option in your release notes. Might be worth adding since it is a new feature. Thanks again.

**Comment by vtst** [comment]
Thanks for the feedback. I did not mention in the release notes, because this new feature is not part of version 1.0.7 (I released it earlier in the day). It will be shipped with version 1.0.8.
