### ISSUE TITLE
Less: Multiple errors instead of undefined mixin errors

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#51]
The following is from forms.less in Bootstrap 2.0.3.

```
#grid > .input (@gridColumnWidth, @gridGutterWidth);
```

The #grid and .input are mixins. The .input takes two arguments.
Note there is a space between .input and '('.

I'm getting 'Multiple markers at this line' instead of just undefined mixin errors.

```
Multiple markers at this line
- mismatched input ')' expecting ':'
- no viable alternative at input '('
- mismatched input '(' expecting '}'
- mismatched input ',' expecting ':'
- mismatched input '@gridGutterWidth' expecting ';'
```

I would expect instead to just get an error that the #grid and .input mixins are undefined.

**Comment by vtst** [comment]
This seems to be correctly handled in the current version of the plugin.
