### ISSUE TITLE
Less: @keyframes rules

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#53]
Bootstrap progress-bars.less defines the following @-rule keyword.

```
@-webkit-keyframes progress-bar-stripes {
    from  { background-position: 40px 0; }
    to    { background-position: 0 0; }
}
```

The @-webkit-keyframes is the wrong color, blue bold. Instead of purple bold italic.

I'm also getting multiple errors with this definition.

Multiple markers at this line for progress-bar-stripes
    - missing ':' at 'progress-bar-stripes'
    - no viable alternative at input '{'

And the following
    mismatched input 'from' expecting ';'
    missing EOF at '}'

**Comment by vtst** [comment]
According to CSS grammar, it seems that '@' is not a valid first character for an identifier.
http://www.w3.org/TR/css3-syntax/#SUBTOK-nmstart
I don't know what to do if there are practical use cases. It seems it would significantly compilcate the parser to handle such a case (because of the disambiguation problem with the variable definitions).

**Comment by mchiocca** [comment]
This seems to be valid LESS since LESS compilers successfully compile it. If you download Twitter Bootstrap and look at progress-bars.less you can see the use case. The above pattern is used to define the following.

@-webkit-keyframes
@-moz-keyframes
@-ms-keyframes
@-o-keyframes

The definitions are all similar. Then, progress-bars-stripes is used as follows.

```
.progress.active .bar {
    -webkit-animation: progress-bar-stripes 2s linear infinite;
       -moz-animation: progress-bar-stripes 2s linear infinite;
        -ms-animation: progress-bar-stripes 2s linear infinite;
         -o-animation: progress-bar-stripes 2s linear infinite;
            animation: progress-bar-stripes 2s linear infinite;
}
```

Admittedly, I don't fully understand the definition or its use in this manner, but it is valid LESS. I've tried to look for the specification of this syntax myself, but haven't found it yet.

**Comment by gossi** [comment]
It's fine to use the @. It's a bit hidden in the TR, but I think I get it. Well, the link where you are pointing at is the grammar for tokenization. There is also the ATKEYWORD defined. If you scroll lower to 4.3.2 Grammer -> Stylesheets this is where it cames back in. You aren't parsing the IDENT of a selector here, but the ATKEYWORD of an at-rule.

Hope that helps, so I'm not sure if I'm right with that.

**Comment by FagnerMartinsBrack** [comment]
The plugin should do the same as the less compiler, warnings included. If the compiler does not throw any message this plugin should not also.

**Comment by vtst** [comment]
Implemented in the codebase.
This was not related to ATKEYWORD. It was just needed to implement support for CSS3 animations syntax.
