### ISSUE TITLE
Less: Errors with mixin that uses when

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#54]
Bootstrap mixins.less has the following.

```
.spanX (@index) when (@index > 0) {
    (~".span@{index}") { .span(@index); }
        .spanX(@index - 1);
}
.spanX (0) {}
```

The string, ".span@{index}" is the wrong color, bold blue, instead of the string color. Is that by design since it looks like a selector?

I'm getting errors

For (~".span@{index}")
    Multiple markers at this line
    - Couldn't resolve reference to VariableCrossReference '@index'.
    - no viable alternative at input '".span@{index}"'
    - mismatched input '(' expecting '}'

I guess the second error is because the .span# (e.g. .span1) mixin is undefined. But, the first error seems wrong since @index is a parameter in the definition of the .spanX mixin.

For .spanX(@index - 1)
    Couldn't resolve reference to VariableCrossReference '@index'.

But @index is a parameter in the .spanX mixin so it should be resolvable.

**Comment by ycfreeman** [comment]
i've encountered the same issue, it looks more like it doesn't validate properly with classes that starts with "("

**Comment by vtst** [comment]
(~".span@{index}") { ... } is not supported by the plugin.
It seems it will disappear in Less 1.4.0, so I do not plan to implement it.
I implemented the new construct .@{var} in bug #107.
