### ISSUE TITLE
import/export of themes

### ISSUE THREAD

**Issue by samuelmolinski** [vtst/ow#57]
some level of transparency to transfer color schemes between IDEs or just easier to edit to match existing themes

**Comment by vtst** [comment]
I'm sorry, but I'm not sure to understand exactly what you want or need. Could you please explain a little bit more?

**Comment by samuelmolinski** [comment]
sorry for being ambiguous.  I was trying your plugin and the first thing I noticed was when I was trying to set the color for the syntax highlighting I was confronted with the tedious task of theme it again to match my existing css colors.  I may have missed it, but I didn't see an easy way to import the color scheme or edit it with hexidecimal values.  this was rather annoying since all my themes where edited in that fashion.  In fact this maybe more of a limitation of Xtext then your plugin, but I am not sure.

Even if you could point me to an XML file with the values that would be great.

**Comment by vtst** [comment]
Thanks for the explanations. This is effectively managed by Xtext. I had a quick look, but I was not able to find the file storing this. You may ask on the Xtext forum.

**Comment by samuelmolinski** [comment]
thanks so much :)
