### ISSUE TITLE
JS: Class Interface bug

### ISSUE THREAD

**Issue by firecow** [vtst/ow#60]
I'm getting this warning, when making an simple interface.
I think it would be best to use goog.nullFunction for interface function declaration, instead of declaring new empty functions for every new prototype function. 
Funny thing is that goog.nullFunction is a empty function, so i don't quite get, why i get this warning.

*\* Interface members can only be empty property declarations, empty functions, or goog.abstractMethod **

``` javascript
goog.provide('test.LivingBeing');

/**
 * @interface
 */
test.LivingBeing = goog.nullFunction;

/**
 * @return {number}
 */
test.LivingBeing.prototype.getAge = goog.nullFunction;
```

**Comment by vtst** [comment]
The warnings are either generated by JSDT or by the Closure compiler. You should check the settings of the Closure compiler, maybe there is something to adjust. You may also try to make a manual compilation with the Closure compiler to see if you have also the warning there.
I tried to reproduce the problem on my computer, but I did not get the warning.

**Comment by deno** [comment]
This is Closure’s error, not OW’s. Interfaces can’t have implementations, so you can’t define a function body or point to one.

goog.abstractMethod is special cased in ClosureCompiler:

http://code.google.com/p/closure-compiler/source/browse/trunk/src/com/google/javascript/jscomp/ClosureCodingConvention.java#254

You can provide custom ClosureCodingConvention if you want to use a different function for abstract methods.

**Comment by vtst** [comment]
So I close this issue.

**Comment by firecow** [comment]
Aha, sorry about that :D I'll use abstractMethod or empty function instead
