### ISSUE TITLE
Less: This URI cannot be resolved for @import statements

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#65]
I'm getting a 'This URI cannot be resolved' error for every @import statement, even the the files being imported are in the same directory as the .less file that is importing them.

Download Twitter Bootstrap from GitHub. Open the less directory where all the .less files are located. Open bootstrap.less. Every @import statement has the URI cannot be resolved error.

The run configuration that executes the LESS compiler works, though. Execute the run configuration on bootstrap.less and it successfully generates bootstrap.css. But the @imports are flagged with the error.

**Comment by vtst** [comment]
Thanks for the bug report. This was an undesirable side effect of the change for issue #55.
I fixed it in the code base.

**Comment by vtst** [comment]
Will be released with version 1.0.7.

**Comment by gossi** [comment]
I got the same error. Though this happens when the import uri is a url, like this:

```
@import url('http://fonts.googleapis.com/css?family=Open+Sans:400,600');
```

Will give me the error above. Looks like it's checking the imports in the filesystem (only)?

Thanks for fixing this for http uris.

**Comment by vtst** [comment]
Only file URLs are supported.
It would be difficult to support network URLs, as it would require to download the file on the fly.

**Comment by gossi** [comment]
This is actually a css file and its a css import statement, so it doesn't need to be downloaded. Obviously there is no .css extension. Because there is a yellow warning sign, this looks like my less files do have errors but apparently, they haven't.

**Comment by vtst** [comment]
Ok, I see. I'm submitting a change so that all non-file URI will be ignored. This should address your problem.
Thanks for the feedback.
