### ISSUE TITLE
Tabs to Spaces 

### ISSUE THREAD

**Issue by dwatts3624** [vtst/ow#69]
I was wondering if it would be possible to control the tab behavior in XText/Less like you can with some other editors in Eclipse (e.g. tab = 2 spaces).

It's not a huge deal.  Your plug-in is really great.  Just thought this would be a nice feature -- trying to stay consistent with Drupal's standards.

Danny

**Comment by vtst** [comment]
Hello,

If I understand correctly your need, I think it is already possible:
- Right click in the editor, and select "Preferences..." in the contextual menu
- Go to the page General > Editors > Text editors
- Edit "Displayed tab width" and "Insert spaces for tab".
