### ISSUE TITLE
Less: Cross-references between files

### ISSUE THREAD

**Issue by eic-zz** [vtst/ow#70]
found in the release notes "Cross-references between files" but not sure how this works in detail.

I am using the stucture similar to Twitter Bootstrap in a PHP project. But every variable or mixin i use (which are defined in an other file), i get a marker/error that the editor cant resolve the reference.

Is it a missunderstanding of the Cross-references-feature or is there something to set up in the eclipse project?

**Comment by mchiocca** [comment]
Are you using the @import statement to import the variables/mixins from the file that you are making the cross-references from? For example, if x.less references a variable or mixin from y.less then you must @import "y.less" in x.less or else the cross reference will be unresolvable.

**Comment by eic-zz** [comment]
Hi mchiocca,

the way you describe works, but this is not the problem.
to expand your example:
I have x.less, which @import y.less and z.less. In y.less i have some mixins in z.less i have some variables.

When i use in a mixin in file y.less some variables from z.less i run in the resolve problem.

It would be nice to have a feature to define a "build path for LESS" in the projectpreferences in Eclipse.

**Comment by mchiocca** [comment]
When you use LESS files in HTML files as per www.lesscss.org, there is no notion of a build or compile path. You must explicitly @import files if you reference any variables and/or mixins from those files. I'm not sure that any IDE that supports LESS has a build/compile path. PHPStorm, for example, supports LESS, but it doesn't implement a build path. I think you must use @import in every .less file for those files that include variables/mixins that you are referencing.

**Comment by eic-zz** [comment]
Just for clarification: Running the LESS compiler works fine. Only the IDE run in problems. 
Maybe "build path" was the wrong term, maybe "include path" is more applicable.

I tested your suggestion to @import in every .less file. This solves the problem in the IDE. But compiling the LESS to CSS every mixin output is spawnd depending on how often the mixins definition files is imported.

**Comment by mchiocca** [comment]
Yes. I understand how using @import in all your files may resolve the IDE issues and cause compilation problems. Again, though, even IDEs that I'm aware of that support LESS, such as PHPStorm, do not implement the notion of an include path. If you were to load the Bootstrap source into an IDE (Eclipse or PHPStorm) you'll see that most files have errors for unresolved variables and mixins. But, bootstrap.less, which basically just uses @import to import all other .less files has no errors in the IDE. An include path that allows you to specify .less files to auto-import in the IDE is an interesting idea, but one that is not implemented as far as I know in any IDE.

**Comment by eic-zz** [comment]
So, back to my opening message it is a missunderstanding by me of the cross-references-feature.

Maybe "include path" will be a feature in a future release.
