### ISSUE TITLE
LESS: Will it work with Xtext 2.3.0?

### ISSUE THREAD

**Issue by Ciantic** [vtst/ow#74]
About to install this Less editor. One thing I noticed that Xtext (not prefixed with "TMF") has version 2.3.0 in the [Xtext update site](http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/). Does this plugin work with newer Xtext?

**Comment by vtst** [comment]
I did not try yet. But in the past, new releases of Xtext did not cause any compatibility issues, so I'd expect it to work fine.

**Comment by vtst** [comment]
I quickly checked, and it seems to work without problem.
