### ISSUE TITLE
@import-once feature is not supported

### ISSUE THREAD

**Issue by IschenkoArtem** [vtst/ow#77]
@import-once very important fix that was introduced in lesscss last month. For IDE it's basically @import.

**Comment by vtst** [comment]
Hi
Do you have a pointer where this directive is defined? I did not see it in the documentation at http://www.lesscss.org/.

**Comment by IschenkoArtem** [comment]
You can see it from commit https://github.com/cloudhead/less.js/commit/88915649179c879048677f6b8d213b4b2756f676, but yep at http://www.lesscss.org/ it's not defined. As from discussions i can see that there was some bugs around this feature (maybe all have been fixed already), but for me it's working just fine (using SimpLESS 1.3, that should update automatically to the latest version of LESS).

**Comment by IschenkoArtem** [comment]
If i use @import in every place where I want to, then my compiled css bloats with duplications or even won't compile at all. Using @import-once really solves this problem, but in a cost of yours IDE support.

**Comment by IschenkoArtem** [comment]
It's my mistake, this feature doesn't work and LESS still has problems with duplicating imports.
