### ISSUE TITLE
Syntax highlighting changes don't take effect until Eclipse is restarted

### ISSUE THREAD

**Issue by rapodaca** [vtst/ow#8]
1) change the color of any syntax element.
2) click 'apply' or 'ok'.
3) nothing changes.
4) restart Eclipse
5) highlighting changes now in effect.

I expected changes to take effect after pressing 'ok'.

**Comment by vtst** [comment]
I was able to reproduce the version, and I'd expect the same behavior as you.
The preference page for configuring colors is not implemented in the soy plugin itself: it is provided by Xtext, the framework for DSL on top of which the plugin is built. The problem might come from Xtext, I'll investigate.

**Comment by vtst** [comment]
As this is an Xtext problem, I'm closing this issue.
