### ISSUE TITLE
Less: Ignore folders

### ISSUE THREAD

**Issue by francisdb** [vtst/ow#80]
I would like the less plugin to ignore certain project folders

for example I have a playframework 1.x project, modules get added to the project/classpath but I'm not interested in errors in these modules' less exceptions so I would like to ignore specific java build path locations

Any other options?

**Comment by vtst** [comment]
As far as I understand, you want to ignore some LESS files from your project? Are these files imported in other LESS files which are not ignored?

**Comment by francisdb** [comment]
A play project with modules has the modules added as resource in eclipse

eg:
project/
project/public/stylesheets/style.less (my less files)
project/modules/less-0.9/samples-and-tests/less-sample/public/stylesheets/error.less (module test less files)

the project/modules is added as an eclipse project resource and is because of that scanned by the plugin

there is (as far as I know) no reference/import possible from my project less files to the module's less files.

Thanks for looking into this!

**Comment by vtst** [comment]
It seems to be doable with Xtext.
See http://www.eclipse.org/forums/index.php/m/824160/
One needs to override org.eclipse.xtext.ui.resource.DefaultResourceUIServiceProvider.canHandle(URI).

**Comment by pbvahlst** [comment]
This would be a really useful feature. Third party libraries such as bootstrap I generating a lot of errors right now. This could maybe be done like the JavaScript validator where you can exclude files or folders from validation.

**Comment by janeklb** [comment]
+1

**Comment by Quevin** [comment]
Same here w/ bootstrap, slumx.

**Comment by vtst** [comment]
This is the same as #176.

**Comment by francisdb** [comment]
Bit annoying that you close the oldest issue instead of the duplicate

**Comment by paulvi** [comment]
@francisdb #176 gives half solution how to implement that.

**Comment by vtst** [comment]
FYI I closed this one because it is more specific (folder) than #176.
