### ISSUE TITLE
Missing support for @lends

### ISSUE THREAD

**Issue by slodko** [vtst/ow#81]
When I try:

```
goog.require('app.model.Character');
javascript
player = new app.model.Character(-1);
utils.complementD(player, 
    /** @lends {app.model.Character} */
       { ... });

player.  '''cursor here'''
```

there are completion proposals only from class app.model.Character.

**Comment by vtst** [comment]
I'm not sure to fully understand the code snippet you provide. But basically the completion proposals are computed using the closure compiler. So, you would get what the closure compiler does of the lends annotation.

If you effectively think there are some missing completion proposals, it would be nice to get a complete and small example which is properly compiled by the closure compiler, and where some completion proposals are missing.
