### ISSUE TITLE
goog.provides, inherits, etc autocompletion?

### ISSUE THREAD

**Issue by bytesandwich** [vtst/ow#83]
I am wondering how difficult it would be to add content assist for the default goog object?

I've never worked on an eclipse plugin, but I'd like to contribute.

**Comment by bytesandwich** [comment]
I'm trying to play around with the source for the plugin, but I can't get the project to recognize the source folder as a java source folder? Is there something special you do to configure this? 

update: I re imported only easy ui, closure.compiler, js.closure, and js.closure.feature without problems

**Comment by vtst** [comment]
> I am wondering how difficult it would be to add content assist for the default goog object?

Do you want closure completion for the function name (goog.provide), or for the argument (e.g. goog.dom in goog.provide('goog.dom'))?

> I'm trying to play around with the source for the plugin, but I can't get the project to recognize the source folder as a java source folder? Is there something special you do to configure this?

Did you try to import the whole project using Eclipse Git plugin?

**Comment by bytesandwich** [comment]
Maybe I have just misconfigured the plugin, but I don't see any proposals for 'goo' (unless I've already required something, and then I see 'google') or 'goog.' . I would think 'goo' would offer 'goog' and 'goog.' would offer 'require', 'provide', 'inherit', etc. 
I would guess that completion for the package name string would be more ambitious. It would be sweet if the plugin could suggest imports like the java content assist engine does, e.g. HashMap -> import java.util.HashMap

**Comment by bytesandwich** [comment]
It appears that 'goog' will autocomplete if at any point goog.require is called?

**Comment by bytesandwich** [comment]
I think #87 will lead to the resolution of this issue.

**Comment by vtst** [comment]
Yes, this is the same as #87. I closed the other one.

**Comment by vtst** [comment]
The goog object is indeed defined only if at least one goog.require statement is included in the file.
I'll try to fix this.

**Comment by vtst** [comment]
This is fixed in the code base, and will be released in the next version of the plugin.

**Comment by bytesandwich** [comment]
thanks!
