### ISSUE TITLE
JS: Unrequired type not recognized as @param

### ISSUE THREAD

**Issue by bytesandwich** [vtst/ow#88]
If a type is only required as a parameter, it is not necessary to require it

Bar.js:

``` javascript
/**
 * @fileoverview Bar takes Foo as a parameter, but shouldn't need to require
 *      Foo
 */

goog.provide('Bar');
//goog.require('Foo');

/**
 * @param {Foo} foo The foo to foo.
 */
Bar = function(foo) {
    foo = foo;
}; 
```

Foo.js:

``` javascript
/**
 * @fileoverview Foo is a type that should be recognizable without requiring
 *      if the Foo object is only received as a parameter
 */
goog.provide('Foo');

/**
 * @constructor
 */
Foo = function() {};
```

**Comment by bytesandwich** [comment]
I think this might have to do with the plugin's caching? I can't find where the plugin caches anything, though.

**Comment by vtst** [comment]
The algorithm used by the plugin in order to detect changes and decide what to recompile is not 100% exact. I made a few simplification for efficiency purpose.
Try in this order:
1. Save the file where the changes have been made.
2. Project > Clean...
3. Restart Eclipse

There is no caching on the file system (except the stripped files with the .ow extension, but this should not be an issue here).

**Comment by bytesandwich** [comment]
No luck with those steps. I think requiring it isn't a big deal. Advanced mode shouldn't include anything from the unnecessary require, anyway.

**Comment by bytesandwich** [comment]
This is actually an issue whose resolution would really improve my experience in the plugin. Frequently I have a Component and a Renderer, and the require cannot go both ways, and the Control file needs to explicitly require the Renderer to set it as the default in the goog.ui.registry. Thus when I manipulate the Control in the Renderer file I can't get autosuggestions or any type knowledge without running the compiler myself outside the plugin and I cannot explicitly require the control in the renderer because that would create a circular dependency. 

I think this issue really breaks the flow of the plugin, because it removes seemingly all its functionality for a portion of the time I'm working. 

Also, do those compromises affect the dependency updating when file 'a' depends on file 'b' in a situation where file 'b' has not been created yet and then becomes created or when file 'b' is changed? It seems that in those situations this compromise also is substantially hindering the sense that the plugin is in control of the environment because file 'a' will not update without explicitly forcing a restart.

**Comment by bytesandwich** [comment]
This issue is a duplicate of #72

**Comment by vtst** [comment]
Thanks for making the link. I'm closing this one.
