### ISSUE TITLE
Soy: let command not recognized

### ISSUE THREAD

**Issue by rapodaca** [vtst/ow#9]
According to this:

http://stackoverflow.com/a/9516927/54426

The "let" command can be used to assign a variable.

Inserting:

{let $foo: 'foo' /}

or

{let $foo: $item /} // where $item is a defined parameter

Generates an error:

"no viable alternative to input "$foo"".

Both version appear to compile fine and do the expected thing.

Could it be that the Soy template library used by the Eclipse plugin is out-of-date?

**Comment by vtst** [comment]
I was not aware of this construct, I used the user documentation to develop the plugin.
I'll implement it. Thanks for the info.

**Comment by vtst** [comment]
This is implemented in the codebase, and will be available in the next release.
