### ISSUE TITLE
Less: Changing Syntax coloring makes your code black on white for the current session

### ISSUE THREAD

**Issue by gossi** [vtst/ow#90]
When changing syntax colors, the code changes to a black and white.

Steps to reproduce:
1. Open a .less file in the Less Editor.
2. Go to preferences, change some settings for the syntax coloring of the Less Editor
3. Hit apply

Watch the code in the background of your opened editor, it turns black on white. To get back the colors, restart eclipse. Hope you can change this.

**Comment by vtst** [comment]
I'm sorry, but this is managed by the Xtext framework, so I cannot solve it in the LESS plugin.
I guess this is the same as issue #8.

**Comment by gossi** [comment]
I made a bugreport over there: https://bugs.eclipse.org/bugs/show_bug.cgi?id=389183

**Comment by vtst** [comment]
I'm reopening, as suggested by the answer to the bugreport.

**Comment by vtst** [comment]
I fixed the issue in the code base. It will be available in the next release.
