### ISSUE TITLE
Soy: Leading space on {template} tag

### ISSUE THREAD

**Issue by jamon** [vtst/ow#94]
The Closure Templates compiler disallows having a leading space in front of the "{template}" or "{/template}" tags, but this isn't caught by the eclipse closure templates plugin as a problem.  This leads to confused developers when they make that mistake :-)  It'd be awesome if detection for that could be added in the future.

Thanks,
Jamon

**Comment by vtst** [comment]
Thanks for the bug report. I'll have a look.

**Comment by vtst** [comment]
Fix in the code base. Will be available in the next release.
