### ISSUE TITLE
Less: Auto compile on save

### ISSUE THREAD

**Issue by gossi** [vtst/ow#95]
I must admit I didn't know about the less compiler, until today. As so, it's a very cool launcher, thus not very useful for production usage, where I compile my less file(s) to css file(s) on every save and see the result in my browser. Would be cool to have such a functionality added by that super useful less plugin.

Something like an option per-project where you can select the less folder(s)/file(s) and the css folder(s)/file(s). And they get automatically compiled after each save. Console is only allocated once an error shows up.

**Comment by eic-zz** [comment]
you can create your own builder(s) per project. i realized this by writing an simple ANT build file with a target that calls the LESS compiler.
Not part of the plugin, but basic Eclipse functionality.

**Comment by dwatts3624** [comment]
I found this article that covers how to do this with SASS: http://www.only10types.com/2012/02/get-eclipse-to-automatically-compile.html

Any hints on making that work with lessc (which is installed and working on my system)?

**Comment by gossi** [comment]
I'm currently using this to autocompile my less: http://stackoverflow.com/questions/7686281/unnoticeable-lesscss-compiler-in-eclipse-pdt/9577888#9577888 which does the job.

The problem, and this plugin can solve this, once there is a compilation error, no chance of seeing this. So, once there is an error during compilation, popup the console view with the nice ui from this plugin.

**Comment by eic-zz** [comment]
@gossi 
I used a workaround to "solve" this:
When the lessc runs in an error, the output css file has a filesize of 0. my build script checks the size of the output css file and fires the fail task if the css has 0.
so error in compilation stops in big red letters in the console.
For me the more painfull problem is that sometimes the compiler gives no information where the error is (but this is a other problem).

**Comment by vtst** [comment]
I indeed think that this is not an issue specific to LESS, and should be handled by some other ways than the plugin.
Thanks nevertheless for the proposal.

**Comment by Ciantic** [comment]
I think this is an issue for the plugin or the docs at least. It compiles when I click the button, surely there is a way to trigger the run configuration on save?

**Comment by Ciantic** [comment]
P.S. One way to do it:
1. Preferences -> Run/Debug -> Launching, set "Save required dirty editors before launching"

Then redefine launch command to save key only for LESS editors:
1. Preferences -> General -> Keys, find the command called "Run" with the icon.
2. press "Copy Command"
3. When: "Editing Xtext source"
4. Binding: "Ctrl+S"

**Comment by gossi** [comment]
I wrote an eclipse plugin to exactly does that. You can find it at: https://github.com/gossi/eclipse-transpiler-plugin

Have fun with it.

@vtst maybe you mind putting a link from the less plugin page to it?

**Comment by paulvi** [comment]
@gossi 
OK, so there was a long story.
